export const sber_business_theme = "\n" +
  ":root {\n" +
  "  --text-primary-hover: #17171793;\n" +
  "  --text-primary-active: #171717C4;\n" +
  "  --text-primary: #171717F5;\n" +
  "  --text-primary-brightness: #2525F6FF;\n" +
  "  --text-secondary-hover: #171717FF;\n" +
  "  --text-secondary-active: #171717AB;\n" +
  "  --text-secondary: #1717178F;\n" +
  "  --text-tertiary-hover: #171717FF;\n" +
  "  --text-tertiary-active: #17171756;\n" +
  "  --text-tertiary: #17171748;\n" +
  "  --text-paragraph-hover: #1717177A;\n" +
  "  --text-paragraph-active: #171717A3;\n" +
  "  --text-paragraph: #171717CC;\n" +
  "  --text-accent-hover: #21A19A;\n" +
  "  --text-accent-active: #005E7F;\n" +
  "  --text-accent: #107F8C;\n" +
  "  --text-accent-minor-hover: #47DC62FF;\n" +
  "  --text-accent-minor-active: #21B03CFF;\n" +
  "  --text-positive-hover: #14B32EFF;\n" +
  "  --text-positive-active: #0C6A1BFF;\n" +
  "  --text-positive: #108E26;\n" +
  "  --text-warning-hover: #FD6B17FF;\n" +
  "  --text-warning-active: #C04802FF;\n" +
  "  --text-warning: #E85702;\n" +
  "  --text-negative-hover: #F54254FF;\n" +
  "  --text-negative-active: #DA0B20FF;\n" +
  "  --text-negative: #F31B31;\n" +
  "  --text-info-hover: #0D96F2FF;\n" +
  "  --text-info-active: #0966A5FF;\n" +
  "  --text-positive-minor-hover: #47DC62FF;\n" +
  "  --text-positive-minor-active: #21B03CFF;\n" +
  "  --text-warning-minor-hover: #FDB790FF;\n" +
  "  --text-warning-minor-active: #FC8240FF;\n" +
  "  --text-negative-minor-hover: #FFB8BFFF;\n" +
  "  --text-negative-minor-active: #FF6675FF;\n" +
  "  --text-info-minor-hover: #7ACAFFFF;\n" +
  "  --text-info-minor-active: #29A9FFFF;\n" +
  "  --text-accent-minor: #28D247;\n" +
  "  --text-info: #0B7ECB;\n" +
  "  --text-positive-minor: #28D247;\n" +
  "  --text-warning-minor: #FD9C68;\n" +
  "  --text-negative-minor: #FF8F9A;\n" +
  "  --text-info-minor: #52BAFF;\n" +
  "  --on-dark-text-primary-hover: #F5F5F593;\n" +
  "  --on-dark-text-primary-active: #F5F5F5C4;\n" +
  "  --on-dark-text-primary: #F5F5F5F5;\n" +
  "  --on-dark-text-primary-brightness: #F6F6F6FF;\n" +
  "  --on-dark-text-secondary-hover: #F5F5F5FF;\n" +
  "  --on-dark-text-secondary-active: #F5F5F5AB;\n" +
  "  --on-dark-text-secondary: #F5F5F58F;\n" +
  "  --on-dark-text-tertiary-hover: #F5F5F5FF;\n" +
  "  --on-dark-text-tertiary-active: #F5F5F556;\n" +
  "  --on-dark-text-tertiary: #F5F5F548;\n" +
  "  --on-dark-text-paragraph-hover: #F5F5F57A;\n" +
  "  --on-dark-text-paragraph-active: #F5F5F5A3;\n" +
  "  --on-dark-text-paragraph: #F5F5F5CC;\n" +
  "  --on-dark-text-accent-hover: #2BD44AFF;\n" +
  "  --on-dark-text-accent-active: #1D9032FF;\n" +
  "  --on-dark-text-accent: #24B23E;\n" +
  "  --on-dark-text-accent-minor-hover: #2BD44AFF;\n" +
  "  --on-dark-text-accent-minor-active: #1D9032FF;\n" +
  "  --on-dark-text-positive-hover: #2BD44AFF;\n" +
  "  --on-dark-text-positive-active: #1D9032FF;\n" +
  "  --on-dark-text-positive: #24B23E;\n" +
  "  --on-dark-text-warning-hover: #FF8B4DFF;\n" +
  "  --on-dark-text-warning-active: #FA5700FF;\n" +
  "  --on-dark-text-warning: #FF7024;\n" +
  "  --on-dark-text-negative-hover: #FF6675FF;\n" +
  "  --on-dark-text-negative-active: #FF142CFF;\n" +
  "  --on-dark-text-negative: #FF3D51;\n" +
  "  --on-dark-text-info-hover: #3FABF3FF;\n" +
  "  --on-dark-text-info-active: #0D84D3FF;\n" +
  "  --on-dark-text-positive-minor-hover: #11A72CFF;\n" +
  "  --on-dark-text-positive-minor-active: #0D8222FF;\n" +
  "  --on-dark-text-warning-minor-hover: #CD5713FF;\n" +
  "  --on-dark-text-warning-minor-active: #A84710FF;\n" +
  "  --on-dark-text-negative-minor-hover: #C2192AFF;\n" +
  "  --on-dark-text-negative-minor-active: #7A101AFF;\n" +
  "  --on-dark-text-info-minor-hover: #1483CCFF;\n" +
  "  --on-dark-text-info-minor-active: #116BA7FF;\n" +
  "  --on-dark-text-accent-minor: #24B23E;\n" +
  "  --on-dark-text-info: #199AF0;\n" +
  "  --on-dark-text-positive-minor: #095C18;\n" +
  "  --on-dark-text-warning-minor: #85380C;\n" +
  "  --on-dark-text-negative-minor: #9C1422;\n" +
  "  --on-dark-text-info-minor: #0D5382;\n" +
  "  --on-light-text-primary-hover: #17171793;\n" +
  "  --on-light-text-primary-active: #171717C4;\n" +
  "  --on-light-text-primary: #171717F5;\n" +
  "  --on-light-text-primary-brightness: #2525F6FF;\n" +
  "  --on-light-text-secondary-hover: #171717FF;\n" +
  "  --on-light-text-secondary-active: #171717AB;\n" +
  "  --on-light-text-secondary: #1717178F;\n" +
  "  --on-light-text-tertiary-hover: #171717FF;\n" +
  "  --on-light-text-tertiary-active: #17171756;\n" +
  "  --on-light-text-tertiary: #17171748;\n" +
  "  --on-light-text-paragraph-hover: #1717177A;\n" +
  "  --on-light-text-paragraph-active: #171717A3;\n" +
  "  --on-light-text-paragraph: #171717CC;\n" +
  "  --on-light-text-accent-hover: #14B32EFF;\n" +
  "  --on-light-text-accent-active: #0C6A1BFF;\n" +
  "  --on-light-text-accent: #108E26;\n" +
  "  --on-light-text-accent-minor-hover: #47DC62FF;\n" +
  "  --on-light-text-accent-minor-active: #21B03CFF;\n" +
  "  --on-light-text-positive-hover: #14B32EFF;\n" +
  "  --on-light-text-positive-active: #0C6A1BFF;\n" +
  "  --on-light-text-positive: #108E26;\n" +
  "  --on-light-text-warning-hover: #FD6B17FF;\n" +
  "  --on-light-text-warning-active: #C04802FF;\n" +
  "  --on-light-text-warning: #E85702;\n" +
  "  --on-light-text-negative-hover: #F54254FF;\n" +
  "  --on-light-text-negative-active: #DA0B20FF;\n" +
  "  --on-light-text-negative: #F31B31;\n" +
  "  --on-light-text-info-hover: #0D96F2FF;\n" +
  "  --on-light-text-info-active: #0966A5FF;\n" +
  "  --on-light-text-positive-minor-hover: #47DC62FF;\n" +
  "  --on-light-text-positive-minor-active: #21B03CFF;\n" +
  "  --on-light-text-warning-minor-hover: #FDB790FF;\n" +
  "  --on-light-text-warning-minor-active: #FC8240FF;\n" +
  "  --on-light-text-negative-minor-hover: #FFB8BFFF;\n" +
  "  --on-light-text-negative-minor-active: #FF6675FF;\n" +
  "  --on-light-text-info-minor-hover: #7ACAFFFF;\n" +
  "  --on-light-text-info-minor-active: #29A9FFFF;\n" +
  "  --on-light-text-info: #0B7ECB;\n" +
  "  --on-light-text-warning-minor: #FD9C68;\n" +
  "  --on-light-text-positive-minor: #28D247;\n" +
  "  --on-light-text-accent-minor: #28D247;\n" +
  "  --on-light-text-negative-minor: #FF8F9A;\n" +
  "  --on-light-text-info-minor: #52BAFF;\n" +
  "  --inverse-text-primary-hover: #F5F5F593;\n" +
  "  --inverse-text-primary-active: #F5F5F5C4;\n" +
  "  --inverse-text-primary: #F5F5F5F5;\n" +
  "  --inverse-text-primary-brightness: #F6F6F6FF;\n" +
  "  --inverse-text-secondary-hover: #F5F5F5FF;\n" +
  "  --inverse-text-secondary-active: #F5F5F5AB;\n" +
  "  --inverse-text-secondary: #F5F5F58F;\n" +
  "  --inverse-text-tertiary-hover: #F5F5F5FF;\n" +
  "  --inverse-text-tertiary-active: #F5F5F556;\n" +
  "  --inverse-text-tertiary: #F5F5F548;\n" +
  "  --inverse-text-paragraph-hover: #F5F5F57A;\n" +
  "  --inverse-text-paragraph-active: #F5F5F5A3;\n" +
  "  --inverse-text-paragraph: #F5F5F5CC;\n" +
  "  --inverse-text-accent-hover: #2BD44AFF;\n" +
  "  --inverse-text-accent-active: #1D9032FF;\n" +
  "  --inverse-text-accent: #24B23E;\n" +
  "  --inverse-text-accent-minor-hover: #11A72CFF;\n" +
  "  --inverse-text-accent-minor-active: #0D8222FF;\n" +
  "  --inverse-text-positive-hover: #2BD44AFF;\n" +
  "  --inverse-text-positive-active: #1D9032FF;\n" +
  "  --inverse-text-positive: #24B23E;\n" +
  "  --inverse-text-warning-hover: #FF8B4DFF;\n" +
  "  --inverse-text-warning-active: #FA5700FF;\n" +
  "  --inverse-text-warning: #FF7024;\n" +
  "  --inverse-text-negative-hover: #FF6675FF;\n" +
  "  --inverse-text-negative-active: #FF142CFF;\n" +
  "  --inverse-text-negative: #FF3D51;\n" +
  "  --inverse-text-info-hover: #3FABF3FF;\n" +
  "  --inverse-text-info-active: #0D84D3FF;\n" +
  "  --inverse-text-positive-minor-hover: #11A72CFF;\n" +
  "  --inverse-text-positive-minor-active: #0D8222FF;\n" +
  "  --inverse-text-warning-minor-hover: #CD5713FF;\n" +
  "  --inverse-text-warning-minor-active: #A84710FF;\n" +
  "  --inverse-text-negative-minor-hover: #C2192AFF;\n" +
  "  --inverse-text-negative-minor-active: #7A101AFF;\n" +
  "  --inverse-text-info-minor-hover: #1483CCFF;\n" +
  "  --inverse-text-info-minor-active: #116BA7FF;\n" +
  "  --inverse-text-accent-minor: #095C18;\n" +
  "  --inverse-text-info: #199AF0;\n" +
  "  --inverse-text-positive-minor: #095C18;\n" +
  "  --inverse-text-warning-minor: #85380C;\n" +
  "  --inverse-text-negative-minor: #9C1422;\n" +
  "  --inverse-text-info-minor: #0D5382;\n" +
  "  --surface-solid-primary-hover: #FAFAFAFF;\n" +
  "  --surface-solid-primary-active: #F0F0F0FF;\n" +
  "  --surface-solid-primary: #F5F5F5;\n" +
  "  --surface-solid-primary-brightness: #F6F6F6FF;\n" +
  "  --surface-solid-secondary-hover: #F7F7F7FF;\n" +
  "  --surface-solid-secondary-active: #E8E8E8FF;\n" +
  "  --surface-solid-secondary: #ECECEC;\n" +
  "  --surface-solid-tertiary-hover: #EDEDEDFF;\n" +
  "  --surface-solid-tertiary-active: #D4D4D4FF;\n" +
  "  --surface-solid-tertiary: #DDDDDD;\n" +
  "  --surface-solid-card-hover: #FFFFFFFF;\n" +
  "  --surface-solid-card-active: #FFFFFFFF;\n" +
  "  --surface-solid-card: #FFFFFFFF;\n" +
  "  --surface-solid-card-brightness: #FFFFFFFF;\n" +
  "  --surface-solid-default-hover: #262626FF;\n" +
  "  --surface-solid-default-active: #030303FF;\n" +
  "  --surface-solid-default: #080808;\n" +
  "  --surface-transparent-primary-hover: #08080800;\n" +
  "  --surface-transparent-primary-active: #0808080A;\n" +
  "  --surface-transparent-primary: #08080805;\n" +
  "  --surface-transparent-secondary-hover: #08080805;\n" +
  "  --surface-transparent-secondary-active: #0808081A;\n" +
  "  --surface-transparent-secondary: #0808080F;\n" +
  "  --surface-transparent-tertiary-hover: #0808080A;\n" +
  "  --surface-transparent-tertiary-active: #08080829;\n" +
  "  --surface-transparent-tertiary: #0808081F;\n" +
  "  --surface-transparent-deep-hover: #0808088F;\n" +
  "  --surface-transparent-deep-active: #080808AD;\n" +
  "  --surface-transparent-deep: #080808A3;\n" +
  "  --surface-transparent-card-hover: #FFFFFFFF;\n" +
  "  --surface-transparent-card-active: #FFFFFFFF;\n" +
  "  --surface-transparent-card: #FFFFFFFF;\n" +
  "  --surface-transparent-card-brightness: #FFFFFFFF;\n" +
  "  --surface-clear-hover: #00000000;\n" +
  "  --surface-clear-active: #00000000;\n" +
  "  --surface-clear: #00000000;\n" +
  "  --surface-accent-hover: #21A19A;\n" +
  "  --surface-accent-active: #005E7F;\n" +
  "  --surface-accent: #107F8C;\n" +
  "  --surface-accent-minor-hover: #B1FBBFFF;\n" +
  "  --surface-accent-minor-active: #8BF99FFF;\n" +
  "  --surface-transparent-accent: #FFFFFFFF;\n" +
  "  --surface-positive-hover: #1EB83AFF;\n" +
  "  --surface-positive-active: #178C2CFF;\n" +
  "  --surface-positive: #1A9E32;\n" +
  "  --surface-warning-hover: #FB782DFF;\n" +
  "  --surface-warning-active: #E65705FF;\n" +
  "  --surface-warning: #FA5F05;\n" +
  "  --surface-negative-hover: #FF5263FF;\n" +
  "  --surface-negative-active: #FF142CFF;\n" +
  "  --surface-negative: #FF293E;\n" +
  "  --surface-info-hover: #1798EEFF;\n" +
  "  --surface-info-active: #0F81CCFF;\n" +
  "  --surface-positive-minor-hover: #B1FBBFFF;\n" +
  "  --surface-positive-minor-active: #8BF99FFF;\n" +
  "  --surface-warning-minor-hover: #FEEFE6FF;\n" +
  "  --surface-warning-minor-active: #FEDCC8FF;\n" +
  "  --surface-negative-minor-hover: #FFF5F6FF;\n" +
  "  --surface-negative-minor-active: #FFD6DAFF;\n" +
  "  --surface-info-minor-hover: #E5F5FFFF;\n" +
  "  --surface-info-minor-active: #C7E9FFFF;\n" +
  "  --surface-transparent-positive-hover: #1A9E320A;\n" +
  "  --surface-transparent-positive-active: #1A9E3229;\n" +
  "  --surface-transparent-warning-hover: #FA5F050A;\n" +
  "  --surface-transparent-warning-active: #FA5F0529;\n" +
  "  --surface-transparent-negative-hover: #FF293E0A;\n" +
  "  --surface-transparent-negative-active: #FF293E29;\n" +
  "  --surface-transparent-info-hover: #118CDF0A;\n" +
  "  --surface-transparent-info-active: #118CDF29;\n" +
  "  --surface-accent-minor: #9EFAAF;\n" +
  "  --surface-info: #118CDF;\n" +
  "  --surface-positive-minor: #9EFAAF;\n" +
  "  --surface-warning-minor: #FEE2D2;\n" +
  "  --surface-negative-minor: #FFE0E3;\n" +
  "  --surface-info-minor: #CFECFF;\n" +
  "  --surface-transparent-positive: #1A9E321F;\n" +
  "  --surface-transparent-warning: #FA5F051F;\n" +
  "  --surface-transparent-negative: #FF293E1F;\n" +
  "  --surface-transparent-info: #118CDF1F;\n" +
  "  --on-dark-surface-solid-primary-hover: #363636FF;\n" +
  "  --on-dark-surface-solid-primary-active: #0D0D0DFF;\n" +
  "  --on-dark-surface-solid-primary: #171717;\n" +
  "  --on-dark-surface-solid-primary-brightness: #252525FF;\n" +
  "  --on-dark-surface-solid-secondary-hover: #3B3B3BFF;\n" +
  "  --on-dark-surface-solid-secondary-active: #1C1C1CFF;\n" +
  "  --on-dark-surface-solid-secondary: #262626;\n" +
  "  --on-dark-surface-solid-tertiary-hover: #4A4A4AFF;\n" +
  "  --on-dark-surface-solid-tertiary-active: #2B2B2BFF;\n" +
  "  --on-dark-surface-solid-tertiary: #363636;\n" +
  "  --on-dark-surface-solid-card-hover: #363636FF;\n" +
  "  --on-dark-surface-solid-card-active: #0D0D0DFF;\n" +
  "  --on-dark-surface-solid-card: #171717;\n" +
  "  --on-dark-surface-solid-card-brightness: #252525FF;\n" +
  "  --on-dark-surface-solid-default-hover: #FFFFFFFF;\n" +
  "  --on-dark-surface-solid-default-active: #F5F5F5FF;\n" +
  "  --on-dark-surface-solid-default: #F9F9F9;\n" +
  "  --on-dark-surface-transparent-primary-hover: #FFFFFF05;\n" +
  "  --on-dark-surface-transparent-primary-active: #FFFFFF1A;\n" +
  "  --on-dark-surface-transparent-primary: #FFFFFF0F;\n" +
  "  --on-dark-surface-transparent-secondary-hover: #FFFFFF0A;\n" +
  "  --on-dark-surface-transparent-secondary-active: #FFFFFF29;\n" +
  "  --on-dark-surface-transparent-secondary: #FFFFFF1F;\n" +
  "  --on-dark-surface-transparent-tertiary-hover: #FFFFFF1F;\n" +
  "  --on-dark-surface-transparent-tertiary-active: #FFFFFF3D;\n" +
  "  --on-dark-surface-transparent-tertiary: #FFFFFF33;\n" +
  "  --on-dark-surface-transparent-deep-hover: #FFFFFF8F;\n" +
  "  --on-dark-surface-transparent-deep-active: #FFFFFFAD;\n" +
  "  --on-dark-surface-transparent-deep: #FFFFFFA3;\n" +
  "  --on-dark-surface-transparent-card-hover: #FFFFFF05;\n" +
  "  --on-dark-surface-transparent-card-active: #FFFFFF1A;\n" +
  "  --on-dark-surface-transparent-card: #FFFFFF0F;\n" +
  "  --on-dark-surface-transparent-card-brightness: #FFFF1DFF;\n" +
  "  --on-dark-surface-clear-hover: #00000000;\n" +
  "  --on-dark-surface-clear-active: #00000000;\n" +
  "  --on-dark-surface-clear: #00000000;\n" +
  "  --on-dark-surface-accent-hover: #1EB83AFF;\n" +
  "  --on-dark-surface-accent-active: #178C2CFF;\n" +
  "  --on-dark-surface-accent: #1A9E32;\n" +
  "  --on-dark-surface-accent-minor-hover: #0E3A16FF;\n" +
  "  --on-dark-surface-accent-minor-active: #061909FF;\n" +
  "  --on-dark-surface-transparent-accent-hover: #1A9E321F;\n" +
  "  --on-dark-surface-transparent-accent-active: #1A9E323D;\n" +
  "  --on-dark-surface-positive-hover: #1EB83AFF;\n" +
  "  --on-dark-surface-positive-active: #178C2CFF;\n" +
  "  --on-dark-surface-positive: #1A9E32;\n" +
  "  --on-dark-surface-warning-hover: #FB782DFF;\n" +
  "  --on-dark-surface-warning-active: #E65705FF;\n" +
  "  --on-dark-surface-warning: #FA5F05;\n" +
  "  --on-dark-surface-negative-hover: #FF5263FF;\n" +
  "  --on-dark-surface-negative-active: #FF142CFF;\n" +
  "  --on-dark-surface-negative: #FF293E;\n" +
  "  --on-dark-surface-info-hover: #1798EEFF;\n" +
  "  --on-dark-surface-info-active: #0F81CCFF;\n" +
  "  --on-dark-surface-positive-minor-hover: #0E3A16FF;\n" +
  "  --on-dark-surface-positive-minor-active: #061909FF;\n" +
  "  --on-dark-surface-warning-minor-hover: #58290EFF;\n" +
  "  --on-dark-surface-warning-minor-active: #2C1507FF;\n" +
  "  --on-dark-surface-negative-minor-hover: #64121AFF;\n" +
  "  --on-dark-surface-negative-minor-active: #380A0FFF;\n" +
  "  --on-dark-surface-info-minor-hover: #10344CFF;\n" +
  "  --on-dark-surface-info-minor-active: #091D2AFF;\n" +
  "  --on-dark-surface-transparent-positive-hover: #1A9E321F;\n" +
  "  --on-dark-surface-transparent-positive-active: #1A9E323D;\n" +
  "  --on-dark-surface-transparent-warning-hover: #FA5F051F;\n" +
  "  --on-dark-surface-transparent-warning-active: #FA5F053D;\n" +
  "  --on-dark-surface-transparent-negative-hover: #FF293E1F;\n" +
  "  --on-dark-surface-transparent-negative-active: #FF293E3D;\n" +
  "  --on-dark-surface-transparent-info-hover: #118CDF1F;\n" +
  "  --on-dark-surface-transparent-info-active: #118CDF3D;\n" +
  "  --on-dark-surface-accent-minor: #0A2B10;\n" +
  "  --on-dark-surface-transparent-accent: #1A9E3233;\n" +
  "  --on-dark-surface-info: #118CDF;\n" +
  "  --on-dark-surface-positive-minor: #0A2B10;\n" +
  "  --on-dark-surface-warning-minor: #3D1D0A;\n" +
  "  --on-dark-surface-negative-minor: #4A0D13;\n" +
  "  --on-dark-surface-info-minor: #0C283B;\n" +
  "  --on-dark-surface-transparent-positive: #1A9E3233;\n" +
  "  --on-dark-surface-transparent-warning: #FA5F0533;\n" +
  "  --on-dark-surface-transparent-negative: #FF293E33;\n" +
  "  --on-dark-surface-transparent-info: #118CDF33;\n" +
  "  --on-light-surface-solid-primary-hover: #FAFAFAFF;\n" +
  "  --on-light-surface-solid-primary-active: #F0F0F0FF;\n" +
  "  --on-light-surface-solid-primary: #F5F5F5;\n" +
  "  --on-light-surface-solid-primary-brightness: #F6F6F6FF;\n" +
  "  --on-light-surface-solid-secondary-hover: #F7F7F7FF;\n" +
  "  --on-light-surface-solid-secondary-active: #E8E8E8FF;\n" +
  "  --on-light-surface-solid-secondary: #ECECEC;\n" +
  "  --on-light-surface-solid-tertiary-hover: #EDEDEDFF;\n" +
  "  --on-light-surface-solid-tertiary-active: #D4D4D4FF;\n" +
  "  --on-light-surface-solid-tertiary: #DDDDDD;\n" +
  "  --on-light-surface-solid-card-hover: #FFFFFFFF;\n" +
  "  --on-light-surface-solid-card-active: #FFFFFFFF;\n" +
  "  --on-light-surface-solid-card: #FFFFFFFF;\n" +
  "  --on-light-surface-solid-card-brightness: #FFFFFFFF;\n" +
  "  --on-light-surface-solid-default-hover: #262626FF;\n" +
  "  --on-light-surface-solid-default-active: #030303FF;\n" +
  "  --on-light-surface-solid-default: #080808;\n" +
  "  --on-light-surface-transparent-primary-hover: #08080800;\n" +
  "  --on-light-surface-transparent-primary-active: #0808080A;\n" +
  "  --on-light-surface-transparent-primary: #08080805;\n" +
  "  --on-light-surface-transparent-secondary-hover: #08080805;\n" +
  "  --on-light-surface-transparent-secondary-active: #0808081A;\n" +
  "  --on-light-surface-transparent-secondary: #0808080F;\n" +
  "  --on-light-surface-transparent-tertiary-hover: #0808080A;\n" +
  "  --on-light-surface-transparent-tertiary-active: #08080829;\n" +
  "  --on-light-surface-transparent-tertiary: #0808081F;\n" +
  "  --on-light-surface-transparent-deep-hover: #0808088F;\n" +
  "  --on-light-surface-transparent-deep-active: #080808AD;\n" +
  "  --on-light-surface-transparent-deep: #080808A3;\n" +
  "  --on-light-surface-transparent-card-hover: #FFFFFFFF;\n" +
  "  --on-light-surface-transparent-card-active: #FFFFFFFF;\n" +
  "  --on-light-surface-transparent-card: #FFFFFFFF;\n" +
  "  --on-light-surface-transparent-card-brightness: #FFFFFFFF;\n" +
  "  --on-light-surface-clear-hover: #00000000;\n" +
  "  --on-light-surface-clear-active: #00000000;\n" +
  "  --on-light-surface-clear: #00000000;\n" +
  "  --on-light-surface-accent-hover: #1EB83AFF;\n" +
  "  --on-light-surface-accent-active: #178C2CFF;\n" +
  "  --on-light-surface-accent: #1A9E32;\n" +
  "  --on-light-surface-accent-minor-hover: #B1FBBFFF;\n" +
  "  --on-light-surface-accent-minor-active: #8BF99FFF;\n" +
  "  --on-light-surface-transparent-accent-hover: #1A9E320A;\n" +
  "  --on-light-surface-transparent-accent-active: #1A9E3229;\n" +
  "  --on-light-surface-positive-hover: #1EB83AFF;\n" +
  "  --on-light-surface-positive-active: #178C2CFF;\n" +
  "  --on-light-surface-positive: #1A9E32;\n" +
  "  --on-light-surface-warning-hover: #FB782DFF;\n" +
  "  --on-light-surface-warning-active: #E65705FF;\n" +
  "  --on-light-surface-warning: #FA5F05;\n" +
  "  --on-light-surface-negative-hover: #FF5263FF;\n" +
  "  --on-light-surface-negative-active: #FF142CFF;\n" +
  "  --on-light-surface-negative: #FF293E;\n" +
  "  --on-light-surface-info-hover: #1798EEFF;\n" +
  "  --on-light-surface-info-active: #0F81CCFF;\n" +
  "  --on-light-surface-positive-minor-hover: #B1FBBFFF;\n" +
  "  --on-light-surface-positive-minor-active: #8BF99FFF;\n" +
  "  --on-light-surface-warning-minor-hover: #FEEFE6FF;\n" +
  "  --on-light-surface-warning-minor-active: #FEDCC8FF;\n" +
  "  --on-light-surface-negative-minor-hover: #FFF5F6FF;\n" +
  "  --on-light-surface-negative-minor-active: #FFD6DAFF;\n" +
  "  --on-light-surface-info-minor-hover: #E5F5FFFF;\n" +
  "  --on-light-surface-info-minor-active: #C7E9FFFF;\n" +
  "  --on-light-surface-transparent-positive-hover: #1A9E320A;\n" +
  "  --on-light-surface-transparent-positive-active: #1A9E3229;\n" +
  "  --on-light-surface-transparent-warning-hover: #FA5F050A;\n" +
  "  --on-light-surface-transparent-warning-active: #FA5F0529;\n" +
  "  --on-light-surface-transparent-negative-hover: #FF293E0A;\n" +
  "  --on-light-surface-transparent-negative-active: #FF293E29;\n" +
  "  --on-light-surface-transparent-info-hover: #118CDF0A;\n" +
  "  --on-light-surface-transparent-info-active: #118CDF29;\n" +
  "  --on-light-surface-accent-minor: #9EFAAF;\n" +
  "  --on-light-surface-transparent-accent: #1A9E321F;\n" +
  "  --on-light-surface-info: #118CDF;\n" +
  "  --on-light-surface-warning-minor: #FEE2D2;\n" +
  "  --on-light-surface-positive-minor: #9EFAAF;\n" +
  "  --on-light-surface-info-minor: #CFECFF;\n" +
  "  --on-light-surface-negative-minor: #FFE0E3;\n" +
  "  --on-light-surface-transparent-positive: #1A9E321F;\n" +
  "  --on-light-surface-transparent-warning: #FA5F051F;\n" +
  "  --on-light-surface-transparent-negative: #FF293E1F;\n" +
  "  --on-light-surface-transparent-info: #118CDF1F;\n" +
  "  --inverse-surface-solid-primary-hover: #363636FF;\n" +
  "  --inverse-surface-solid-primary-active: #0D0D0DFF;\n" +
  "  --inverse-surface-solid-primary: #171717;\n" +
  "  --inverse-surface-solid-primary-brightness: #252525FF;\n" +
  "  --inverse-surface-solid-secondary-hover: #3B3B3BFF;\n" +
  "  --inverse-surface-solid-secondary-active: #1C1C1CFF;\n" +
  "  --inverse-surface-solid-secondary: #262626;\n" +
  "  --inverse-surface-solid-tertiary-hover: #4A4A4AFF;\n" +
  "  --inverse-surface-solid-tertiary-active: #2B2B2BFF;\n" +
  "  --inverse-surface-solid-tertiary: #363636;\n" +
  "  --inverse-surface-solid-card-hover: #363636FF;\n" +
  "  --inverse-surface-solid-card-active: #0D0D0DFF;\n" +
  "  --inverse-surface-solid-card: #171717;\n" +
  "  --inverse-surface-solid-card-brightness: #252525FF;\n" +
  "  --inverse-surface-solid-default-hover: #FFFFFFFF;\n" +
  "  --inverse-surface-solid-default-active: #F5F5F5FF;\n" +
  "  --inverse-surface-solid-default: #F9F9F9;\n" +
  "  --inverse-surface-transparent-primary-hover: #FFFFFF05;\n" +
  "  --inverse-surface-transparent-primary-active: #FFFFFF1A;\n" +
  "  --inverse-surface-transparent-primary: #FFFFFF0F;\n" +
  "  --inverse-surface-transparent-secondary-hover: #FFFFFF0A;\n" +
  "  --inverse-surface-transparent-secondary-active: #FFFFFF29;\n" +
  "  --inverse-surface-transparent-secondary: #FFFFFF1F;\n" +
  "  --inverse-surface-transparent-tertiary-hover: #FFFFFF1F;\n" +
  "  --inverse-surface-transparent-tertiary-active: #FFFFFF3D;\n" +
  "  --inverse-surface-transparent-tertiary: #FFFFFF33;\n" +
  "  --inverse-surface-transparent-deep-hover: #FFFFFF8F;\n" +
  "  --inverse-surface-transparent-deep-active: #FFFFFFAD;\n" +
  "  --inverse-surface-transparent-deep: #FFFFFFA3;\n" +
  "  --inverse-surface-transparent-card-hover: #FFFFFF05;\n" +
  "  --inverse-surface-transparent-card-active: #FFFFFF1A;\n" +
  "  --inverse-surface-transparent-card: #FFFFFF0F;\n" +
  "  --inverse-surface-transparent-card-brightness: #FFFF1DFF;\n" +
  "  --inverse-surface-clear-hover: #00000000;\n" +
  "  --inverse-surface-clear-active: #00000000;\n" +
  "  --inverse-surface-clear: #00000000;\n" +
  "  --inverse-surface-accent-hover: #1EB83AFF;\n" +
  "  --inverse-surface-accent-active: #178C2CFF;\n" +
  "  --inverse-surface-accent: #1A9E32;\n" +
  "  --inverse-surface-accent-minor-hover: #0E3A16FF;\n" +
  "  --inverse-surface-accent-minor-active: #061909FF;\n" +
  "  --inverse-surface-transparent-accent-hover: #1A9E321F;\n" +
  "  --inverse-surface-transparent-accent-active: #1A9E323D;\n" +
  "  --inverse-surface-positive-hover: #1EB83AFF;\n" +
  "  --inverse-surface-positive-active: #178C2CFF;\n" +
  "  --inverse-surface-positive: #1A9E32;\n" +
  "  --inverse-surface-warning-hover: #FB782DFF;\n" +
  "  --inverse-surface-warning-active: #E65705FF;\n" +
  "  --inverse-surface-warning: #FA5F05;\n" +
  "  --inverse-surface-negative-hover: #FF5263FF;\n" +
  "  --inverse-surface-negative-active: #FF142CFF;\n" +
  "  --inverse-surface-negative: #FF293E;\n" +
  "  --inverse-surface-info-hover: #1798EEFF;\n" +
  "  --inverse-surface-info-active: #0F81CCFF;\n" +
  "  --inverse-surface-positive-minor-hover: #0E3A16FF;\n" +
  "  --inverse-surface-positive-minor-active: #061909FF;\n" +
  "  --inverse-surface-warning-minor-hover: #58290EFF;\n" +
  "  --inverse-surface-warning-minor-active: #2C1507FF;\n" +
  "  --inverse-surface-negative-minor-hover: #64121AFF;\n" +
  "  --inverse-surface-negative-minor-active: #380A0FFF;\n" +
  "  --inverse-surface-info-minor-hover: #10344CFF;\n" +
  "  --inverse-surface-info-minor-active: #091D2AFF;\n" +
  "  --inverse-surface-transparent-positive-hover: #1A9E321F;\n" +
  "  --inverse-surface-transparent-positive-active: #1A9E323D;\n" +
  "  --inverse-surface-transparent-warning-hover: #FA5F051F;\n" +
  "  --inverse-surface-transparent-warning-active: #FA5F053D;\n" +
  "  --inverse-surface-transparent-negative-hover: #FF293E1F;\n" +
  "  --inverse-surface-transparent-negative-active: #FF293E3D;\n" +
  "  --inverse-surface-transparent-info-hover: #118CDF1F;\n" +
  "  --inverse-surface-transparent-info-active: #118CDF3D;\n" +
  "  --inverse-surface-accent-minor: #0A2B10;\n" +
  "  --inverse-surface-transparent-accent: #1A9E3233;\n" +
  "  --inverse-surface-info: #118CDF;\n" +
  "  --inverse-surface-positive-minor: #0A2B10;\n" +
  "  --inverse-surface-warning-minor: #3D1D0A;\n" +
  "  --inverse-surface-negative-minor: #4A0D13;\n" +
  "  --inverse-surface-info-minor: #0C283B;\n" +
  "  --inverse-surface-transparent-positive: #1A9E3233;\n" +
  "  --inverse-surface-transparent-warning: #FA5F0533;\n" +
  "  --inverse-surface-transparent-negative: #FF293E33;\n" +
  "  --inverse-surface-transparent-info: #118CDF33;\n" +
  "  --background-primary: #F9F9F9;\n" +
  "  --background-primary-brightness: #F9F9F9FF;\n" +
  "  --dark-background-primary: #080808;\n" +
  "  --light-background-primary: #F9F9F9;\n" +
  "  --inverse-background-primary: #080808;\n" +
  "  --inverse-background-primary-brightness: #171717FF;\n" +
  "  --overlay-soft: #F9F9F98F;\n" +
  "  --overlay-hard: #F9F9F9F5;\n" +
  "  --overlay-blur: #F9F9F947;\n" +
  "  --on-dark-overlay-soft: #0808088F;\n" +
  "  --on-dark-overlay-hard: #080808F5;\n" +
  "  --on-dark-overlay-blur: #08080847;\n" +
  "  --on-light-overlay-soft: #F9F9F98F;\n" +
  "  --on-light-overlay-hard: #F9F9F9F5;\n" +
  "  --on-light-overlay-blur: #F9F9F947;\n" +
  "  --inverse-overlay-soft: #0808088F;\n" +
  "  --inverse-overlay-hard: #080808F5;\n" +
  "  --inverse-overlay-blur: #08080847;\n" +
  "  --outline-solid-primary-hover: #000000FF;\n" +
  "  --outline-solid-primary-active: #B3B3B3FF;\n" +
  "  --outline-solid-secondary-hover: #000000FF;\n" +
  "  --outline-solid-secondary-active: #757575FF;\n" +
  "  --outline-solid-tertiary-hover: #000000FF;\n" +
  "  --outline-solid-tertiary-active: #595959FF;\n" +
  "  --outline-transparent-default-hover: #000000FF;\n" +
  "  --outline-transparent-default-active: #CCCCCCFF;\n" +
  "  --outline-transparent-primary-hover: #000000FF;\n" +
  "  --outline-transparent-primary-active: #CCCCCCFF;\n" +
  "  --outline-transparent-secondary-hover: #000000FF;\n" +
  "  --outline-transparent-secondary-active: #CCCCCCFF;\n" +
  "  --outline-transparent-tertiary-hover: #000000FF;\n" +
  "  --outline-transparent-tertiary-active: #CCCCCCFF;\n" +
  "  --outline-clear-hover: #00000000;\n" +
  "  --outline-clear-active: #00000000;\n" +
  "  --outline-accent-hover: #14B32EFF;\n" +
  "  --outline-accent-active: #0C6A1BFF;\n" +
  "  --outline-accent-minor-hover: #47DC62FF;\n" +
  "  --outline-accent-minor-active: #21B03CFF;\n" +
  "  --outline-transparent-accent-hover: #108E25FF;\n" +
  "  --outline-transparent-accent-active: #108E253D;\n" +
  "  --outline-promo-hover: #000000FF;\n" +
  "  --outline-promo-active: #CCCCCCFF;\n" +
  "  --outline-promo-minor-hover: #000000FF;\n" +
  "  --outline-promo-minor-active: #CCCCCCFF;\n" +
  "  --outline-positive-hover: #14B32EFF;\n" +
  "  --outline-positive-active: #0C6A1BFF;\n" +
  "  --outline-warning-hover: #FD6B17FF;\n" +
  "  --outline-warning-active: #C04802FF;\n" +
  "  --outline-negative-hover: #F54254FF;\n" +
  "  --outline-negative-active: #DA0B20FF;\n" +
  "  --outline-info-hover: #0D96F2FF;\n" +
  "  --outline-info-active: #0966A5FF;\n" +
  "  --outline-positive-minor-hover: #47DC62FF;\n" +
  "  --outline-positive-minor-active: #21B03CFF;\n" +
  "  --outline-warning-minor-hover: #FDB790FF;\n" +
  "  --outline-warning-minor-active: #FC8240FF;\n" +
  "  --outline-negative-minor-hover: #FFB8BFFF;\n" +
  "  --outline-negative-minor-active: #FF6675FF;\n" +
  "  --outline-info-minor-hover: #7ACAFFFF;\n" +
  "  --outline-info-minor-active: #29A9FFFF;\n" +
  "  --outline-transparent-positive-hover: #108E25FF;\n" +
  "  --outline-transparent-positive-active: #108E253D;\n" +
  "  --outline-transparent-warning-hover: #E85702FF;\n" +
  "  --outline-transparent-warning-active: #E857023D;\n" +
  "  --outline-transparent-negative-hover: #F31B31FF;\n" +
  "  --outline-transparent-negative-active: #F31B313D;\n" +
  "  --outline-transparent-info-hover: #0B7ECBFF;\n" +
  "  --outline-transparent-info-active: #0B7ECB3D;\n" +
  "  --outline-clear: #00000000;\n" +
  "  --outline-solid-primary: #DDDDDD;\n" +
  "  --outline-solid-secondary: #949494;\n" +
  "  --outline-solid-tertiary: #707070;\n" +
  "  --outline-accent: #108E26;\n" +
  "  --outline-accent-minor: #28D247;\n" +
  "  --outline-transparent-accent: #108E2633;\n" +
  "  --outline-warning: #E85702;\n" +
  "  --outline-positive: #108E26;\n" +
  "  --outline-transparent-positive: #108E2633;\n" +
  "  --outline-negative: #F31B31;\n" +
  "  --outline-info: #0B7ECB;\n" +
  "  --outline-positive-minor: #28D247;\n" +
  "  --outline-warning-minor: #FD9C68;\n" +
  "  --outline-negative-minor: #FF8F9A;\n" +
  "  --outline-info-minor: #52BAFF;\n" +
  "  --outline-transparent-warning: #E8570233;\n" +
  "  --outline-transparent-negative: #F31B3133;\n" +
  "  --outline-transparent-info: #0B7ECB33;\n" +
  "  --on-dark-outline-solid-primary-hover: #787878FF;\n" +
  "  --on-dark-outline-solid-primary-active: #4F4F4FFF;\n" +
  "  --on-dark-outline-solid-secondary-hover: #878787FF;\n" +
  "  --on-dark-outline-solid-secondary-active: #5E5E5EFF;\n" +
  "  --on-dark-outline-solid-tertiary-hover: #000000FF;\n" +
  "  --on-dark-outline-solid-tertiary-active: #595959FF;\n" +
  "  --on-dark-outline-transparent-default-hover: #000000FF;\n" +
  "  --on-dark-outline-transparent-default-active: #CCCCCCFF;\n" +
  "  --on-dark-outline-transparent-primary-hover: #000000FF;\n" +
  "  --on-dark-outline-transparent-primary-active: #CCCCCCFF;\n" +
  "  --on-dark-outline-transparent-secondary-hover: #000000FF;\n" +
  "  --on-dark-outline-transparent-secondary-active: #CCCCCCFF;\n" +
  "  --on-dark-outline-transparent-tertiary-hover: #000000FF;\n" +
  "  --on-dark-outline-transparent-tertiary-active: #CCCCCCFF;\n" +
  "  --on-dark-outline-clear-hover: #00000000;\n" +
  "  --on-dark-outline-clear-active: #00000000;\n" +
  "  --on-dark-outline-accent-hover: #2BD44AFF;\n" +
  "  --on-dark-outline-accent-active: #1D9032FF;\n" +
  "  --on-dark-outline-accent-minor-hover: #11A72CFF;\n" +
  "  --on-dark-outline-accent-minor-active: #0D8222FF;\n" +
  "  --on-dark-outline-transparent-accent-hover: #24B23EFF;\n" +
  "  --on-dark-outline-transparent-accent-active: #24B23E56;\n" +
  "  --on-dark-outline-promo-hover: #000000FF;\n" +
  "  --on-dark-outline-promo-active: #CCCCCCFF;\n" +
  "  --on-dark-outline-promo-minor-hover: #000000FF;\n" +
  "  --on-dark-outline-promo-minor-active: #CCCCCCFF;\n" +
  "  --on-dark-outline-positive-hover: #2BD44AFF;\n" +
  "  --on-dark-outline-positive-active: #1D9032FF;\n" +
  "  --on-dark-outline-warning-hover: #FF8B4DFF;\n" +
  "  --on-dark-outline-warning-active: #FA5700FF;\n" +
  "  --on-dark-outline-negative-hover: #FF6675FF;\n" +
  "  --on-dark-outline-negative-active: #FF142CFF;\n" +
  "  --on-dark-outline-info-hover: #3FABF3FF;\n" +
  "  --on-dark-outline-info-active: #0D84D3FF;\n" +
  "  --on-dark-outline-positive-minor-hover: #11A72CFF;\n" +
  "  --on-dark-outline-positive-minor-active: #0D8222FF;\n" +
  "  --on-dark-outline-warning-minor-hover: #FF8B4DFF;\n" +
  "  --on-dark-outline-warning-minor-active: #FA5700FF;\n" +
  "  --on-dark-outline-negative-minor-hover: #FF6675FF;\n" +
  "  --on-dark-outline-negative-minor-active: #FF142CFF;\n" +
  "  --on-dark-outline-info-minor-hover: #3FABF3FF;\n" +
  "  --on-dark-outline-info-minor-active: #0D84D3FF;\n" +
  "  --on-dark-outline-transparent-positive-hover: #24B23EFF;\n" +
  "  --on-dark-outline-transparent-positive-active: #24B23E56;\n" +
  "  --on-dark-outline-transparent-warning-hover: #FF7024FF;\n" +
  "  --on-dark-outline-transparent-warning-active: #FF702456;\n" +
  "  --on-dark-outline-transparent-negative-hover: #FF3D51FF;\n" +
  "  --on-dark-outline-transparent-negative-active: #FF3D5156;\n" +
  "  --on-dark-outline-transparent-info-hover: #199AF0FF;\n" +
  "  --on-dark-outline-transparent-info-active: #199AF056;\n" +
  "  --on-dark-outline-clear: #00000000;\n" +
  "  --on-dark-outline-solid-primary: #262626;\n" +
  "  --on-dark-outline-solid-secondary: #363636;\n" +
  "  --on-dark-outline-solid-tertiary: #707070;\n" +
  "  --on-dark-outline-accent: #24B23E;\n" +
  "  --on-dark-outline-accent-minor: #095C18;\n" +
  "  --on-dark-outline-transparent-accent: #24B23E47;\n" +
  "  --on-dark-outline-transparent-positive: #24B23E47;\n" +
  "  --on-dark-outline-positive: #24B23E;\n" +
  "  --on-dark-outline-warning: #FF7024;\n" +
  "  --on-dark-outline-negative: #FF3D51;\n" +
  "  --on-dark-outline-info: #199AF0;\n" +
  "  --on-dark-outline-positive-minor: #095C18;\n" +
  "  --on-dark-outline-warning-minor: #FF7024;\n" +
  "  --on-dark-outline-negative-minor: #FF3D51;\n" +
  "  --on-dark-outline-info-minor: #199AF0;\n" +
  "  --on-dark-outline-transparent-warning: #FF702447;\n" +
  "  --on-dark-outline-transparent-negative: #FF3D5147;\n" +
  "  --on-dark-outline-transparent-info: #199AF047;\n" +
  "  --on-light-outline-solid-primary-hover: #000000FF;\n" +
  "  --on-light-outline-solid-primary-active: #B3B3B3FF;\n" +
  "  --on-light-outline-solid-secondary-hover: #000000FF;\n" +
  "  --on-light-outline-solid-secondary-active: #757575FF;\n" +
  "  --on-light-outline-solid-tertiary-hover: #000000FF;\n" +
  "  --on-light-outline-solid-tertiary-active: #595959FF;\n" +
  "  --on-light-outline-transparent-default-hover: #000000FF;\n" +
  "  --on-light-outline-transparent-default-active: #CCCCCCFF;\n" +
  "  --on-light-outline-transparent-primary-hover: #000000FF;\n" +
  "  --on-light-outline-transparent-primary-active: #CCCCCCFF;\n" +
  "  --on-light-outline-transparent-secondary-hover: #000000FF;\n" +
  "  --on-light-outline-transparent-secondary-active: #CCCCCCFF;\n" +
  "  --on-light-outline-transparent-tertiary-hover: #000000FF;\n" +
  "  --on-light-outline-transparent-tertiary-active: #CCCCCCFF;\n" +
  "  --on-light-outline-clear-hover: #00000000;\n" +
  "  --on-light-outline-clear-active: #00000000;\n" +
  "  --on-light-outline-accent-hover: #14B32EFF;\n" +
  "  --on-light-outline-accent-active: #0C6A1BFF;\n" +
  "  --on-light-outline-accent-minor-hover: #47DC62FF;\n" +
  "  --on-light-outline-accent-minor-active: #21B03CFF;\n" +
  "  --on-light-outline-transparent-accent-hover: #108E25FF;\n" +
  "  --on-light-outline-transparent-accent-active: #108E253D;\n" +
  "  --on-light-outline-promo-hover: #000000FF;\n" +
  "  --on-light-outline-promo-active: #CCCCCCFF;\n" +
  "  --on-light-outline-promo-minor-hover: #000000FF;\n" +
  "  --on-light-outline-promo-minor-active: #CCCCCCFF;\n" +
  "  --on-light-outline-positive-hover: #14B32EFF;\n" +
  "  --on-light-outline-positive-active: #0C6A1BFF;\n" +
  "  --on-light-outline-warning-hover: #FD6B17FF;\n" +
  "  --on-light-outline-warning-active: #C04802FF;\n" +
  "  --on-light-outline-negative-hover: #F54254FF;\n" +
  "  --on-light-outline-negative-active: #DA0B20FF;\n" +
  "  --on-light-outline-info-hover: #0D96F2FF;\n" +
  "  --on-light-outline-info-active: #0966A5FF;\n" +
  "  --on-light-outline-positive-minor-hover: #47DC62FF;\n" +
  "  --on-light-outline-positive-minor-active: #21B03CFF;\n" +
  "  --on-light-outline-warning-minor-hover: #FDB790FF;\n" +
  "  --on-light-outline-warning-minor-active: #FC8240FF;\n" +
  "  --on-light-outline-negative-minor-hover: #FFB8BFFF;\n" +
  "  --on-light-outline-negative-minor-active: #FF6675FF;\n" +
  "  --on-light-outline-info-minor-hover: #7ACAFFFF;\n" +
  "  --on-light-outline-info-minor-active: #29A9FFFF;\n" +
  "  --on-light-outline-transparent-positive-hover: #108E25FF;\n" +
  "  --on-light-outline-transparent-positive-active: #108E253D;\n" +
  "  --on-light-outline-transparent-warning-hover: #E85702FF;\n" +
  "  --on-light-outline-transparent-warning-active: #E857023D;\n" +
  "  --on-light-outline-transparent-negative-hover: #F31B31FF;\n" +
  "  --on-light-outline-transparent-negative-active: #F31B313D;\n" +
  "  --on-light-outline-transparent-info-hover: #0B7ECBFF;\n" +
  "  --on-light-outline-transparent-info-active: #0B7ECB3D;\n" +
  "  --on-light-outline-clear: #00000000;\n" +
  "  --on-light-outline-transparent-accent: #108E2633;\n" +
  "  --on-light-outline-positive: #108E26;\n" +
  "  --on-light-outline-transparent-positive: #108E2633;\n" +
  "  --on-light-outline-transparent-warning: #E8570233;\n" +
  "  --on-light-outline-transparent-negative: #F31B3133;\n" +
  "  --on-light-outline-transparent-info: #0B7ECB33;\n" +
  "  --on-light-outline-solid-primary: #DDDDDD;\n" +
  "  --on-light-outline-solid-secondary: #949494;\n" +
  "  --on-light-outline-solid-tertiary: #707070;\n" +
  "  --on-light-outline-accent: #108E26;\n" +
  "  --on-light-outline-accent-minor: #28D247;\n" +
  "  --on-light-outline-warning: #E85702;\n" +
  "  --on-light-outline-negative: #F31B31;\n" +
  "  --on-light-outline-info: #0B7ECB;\n" +
  "  --on-light-outline-positive-minor: #28D247;\n" +
  "  --on-light-outline-warning-minor: #FD9C68;\n" +
  "  --on-light-outline-negative-minor: #FF8F9A;\n" +
  "  --on-light-outline-info-minor: #52BAFF;\n" +
  "  --inverse-outline-solid-primary-hover: #787878FF;\n" +
  "  --inverse-outline-solid-primary-active: #4F4F4FFF;\n" +
  "  --inverse-outline-solid-secondary-hover: #878787FF;\n" +
  "  --inverse-outline-solid-secondary-active: #5E5E5EFF;\n" +
  "  --inverse-outline-solid-tertiary-hover: #000000FF;\n" +
  "  --inverse-outline-solid-tertiary-active: #595959FF;\n" +
  "  --inverse-outline-transparent-default-hover: #000000FF;\n" +
  "  --inverse-outline-transparent-default-active: #CCCCCCFF;\n" +
  "  --inverse-outline-transparent-primary-hover: #000000FF;\n" +
  "  --inverse-outline-transparent-primary-active: #CCCCCCFF;\n" +
  "  --inverse-outline-transparent-secondary-hover: #000000FF;\n" +
  "  --inverse-outline-transparent-secondary-active: #CCCCCCFF;\n" +
  "  --inverse-outline-transparent-tertiary-hover: #000000FF;\n" +
  "  --inverse-outline-transparent-tertiary-active: #CCCCCCFF;\n" +
  "  --inverse-outline-clear-hover: #00000000;\n" +
  "  --inverse-outline-clear-active: #00000000;\n" +
  "  --inverse-outline-accent-hover: #2BD44AFF;\n" +
  "  --inverse-outline-accent-active: #1D9032FF;\n" +
  "  --inverse-outline-accent-minor-hover: #11A72CFF;\n" +
  "  --inverse-outline-accent-minor-active: #0D8222FF;\n" +
  "  --inverse-outline-transparent-accent-hover: #24B23EFF;\n" +
  "  --inverse-outline-transparent-accent-active: #24B23E56;\n" +
  "  --inverse-outline-promo-hover: #000000FF;\n" +
  "  --inverse-outline-promo-active: #CCCCCCFF;\n" +
  "  --inverse-outline-promo-minor-hover: #000000FF;\n" +
  "  --inverse-outline-promo-minor-active: #CCCCCCFF;\n" +
  "  --inverse-outline-positive-hover: #2BD44AFF;\n" +
  "  --inverse-outline-positive-active: #1D9032FF;\n" +
  "  --inverse-outline-warning-hover: #FF8B4DFF;\n" +
  "  --inverse-outline-warning-active: #FA5700FF;\n" +
  "  --inverse-outline-negative-hover: #FF6675FF;\n" +
  "  --inverse-outline-negative-active: #FF142CFF;\n" +
  "  --inverse-outline-info-hover: #3FABF3FF;\n" +
  "  --inverse-outline-info-active: #0D84D3FF;\n" +
  "  --inverse-outline-positive-minor-hover: #11A72CFF;\n" +
  "  --inverse-outline-positive-minor-active: #0D8222FF;\n" +
  "  --inverse-outline-warning-minor-hover: #CD5713FF;\n" +
  "  --inverse-outline-warning-minor-active: #A84710FF;\n" +
  "  --inverse-outline-negative-minor-hover: #C2192AFF;\n" +
  "  --inverse-outline-negative-minor-active: #7A101AFF;\n" +
  "  --inverse-outline-info-minor-hover: #1483CCFF;\n" +
  "  --inverse-outline-info-minor-active: #116BA7FF;\n" +
  "  --inverse-outline-transparent-positive-hover: #24B23EFF;\n" +
  "  --inverse-outline-transparent-positive-active: #24B23E56;\n" +
  "  --inverse-outline-transparent-warning-hover: #FF7024FF;\n" +
  "  --inverse-outline-transparent-warning-active: #FF702456;\n" +
  "  --inverse-outline-transparent-negative-hover: #FF3D51FF;\n" +
  "  --inverse-outline-transparent-negative-active: #FF3D5156;\n" +
  "  --inverse-outline-transparent-info-hover: #199AF0FF;\n" +
  "  --inverse-outline-transparent-info-active: #199AF056;\n" +
  "  --inverse-outline-clear: #00000000;\n" +
  "  --inverse-outline-transparent-accent: #24B23E47;\n" +
  "  --inverse-outline-transparent-positive: #24B23E47;\n" +
  "  --inverse-outline-transparent-warning: #FF702447;\n" +
  "  --inverse-outline-transparent-negative: #FF3D5147;\n" +
  "  --inverse-outline-transparent-info: #199AF047;\n" +
  "  --inverse-outline-solid-primary: #262626;\n" +
  "  --inverse-outline-solid-secondary: #363636;\n" +
  "  --inverse-outline-solid-tertiary: #707070;\n" +
  "  --inverse-outline-accent: #24B23E;\n" +
  "  --inverse-outline-accent-minor: #095C18;\n" +
  "  --inverse-outline-positive: #24B23E;\n" +
  "  --inverse-outline-warning: #FF7024;\n" +
  "  --inverse-outline-negative: #FF3D51;\n" +
  "  --inverse-outline-info: #199AF0;\n" +
  "  --inverse-outline-positive-minor: #095C18;\n" +
  "  --inverse-outline-warning-minor: #85380C;\n" +
  "  --inverse-outline-negative-minor: #9C1422;\n" +
  "  --inverse-outline-info-minor: #0D5382;\n" +
  "  color: var(--text-primary);\n" +
  "  background-color: var(--background-primary);\n" +
  "}\n" +
  "\n" +
  ":root {\n" +
  "  --text-accent-gradient-hover: #000000FF;\n" +
  "  --text-accent-gradient-active: #CCCCCCFF;\n" +
  "  --text-accent-gradient: linear-gradient(45.00deg, #0D8523FF 0%, #0DA8ABFF 100%);\n" +
  "  --on-dark-text-accent-gradient-hover: #000000FF;\n" +
  "  --on-dark-text-accent-gradient-active: #CCCCCCFF;\n" +
  "  --on-dark-text-accent-gradient: linear-gradient(45.00deg, #1A9E32FF 0%, #04C6C9FF 99.688%);\n" +
  "  --on-light-text-accent-gradient-hover: #000000FF;\n" +
  "  --on-light-text-accent-gradient-active: #CCCCCCFF;\n" +
  "  --on-light-text-accent-gradient: linear-gradient(45.00deg, #0D8523FF 0%, #0DA8ABFF 100%);\n" +
  "  --inverse-text-accent-gradient-hover: #000000FF;\n" +
  "  --inverse-text-accent-gradient-active: #CCCCCCFF;\n" +
  "  --inverse-text-accent-gradient: linear-gradient(45.00deg, #1A9E32FF 0%, #04C6C9FF 99.688%);\n" +
  "  --surface-accent-gradient-hover: #FFFFFFFF;\n" +
  "  --surface-accent-gradient-active: #FFFFFFFF;\n" +
  "  --surface-accent-gradient: linear-gradient(45.00deg, #0D8523FF 0%, #0DA8ABFF 100%);\n" +
  "  --surface-skeleton-gradient: linear-gradient(90deg, #08080817 0%, #08080814 6.25%, #0808080D 12.5%, #08080803 25%, #0808080D 37.5%, #08080814 43.75%, #08080817 50%, #08080814 56.25%, #0808080D 62.5%, #08080803 75%, #0808080D 87.5%, #08080814 93.75%, #08080817 100%);\n" +
  "  --surface-skeleton-gradient-hover: #FFFFFFFF;\n" +
  "  --surface-skeleton-gradient-active: #FFFFFFFF;\n" +
  "  --surface-skeleton-deep-gradient: linear-gradient(90deg, #0808085C 0%, #08080852 6.25%, #08080833 12.5%, #0808080A 25%, #08080833 37.5%, #08080852 43.75%, #0808085C 50%, #08080814 56.25%, #08080833 62.5%, #0808080A 75%, #08080833 87.5%, #08080852 93.75%, #0808085C 100%);\n" +
  "  --surface-skeleton-deep-gradient-hover: #FFFFFFFF;\n" +
  "  --surface-skeleton-deep-gradient-active: #FFFFFFFF;\n" +
  "  --on-dark-surface-accent-gradient-hover: #FFFFFFFF;\n" +
  "  --on-dark-surface-accent-gradient-active: #FFFFFFFF;\n" +
  "  --on-dark-surface-accent-gradient: linear-gradient(45.00deg, #1A9E32FF 0.323%, #04C6C9FF 100%);\n" +
  "  --on-dark-surface-skeleton-gradient: linear-gradient(90deg, #FFFFFF17 0%, #FFFFFF14 6.25%, #FFFFFF0D 12.5%, #FFFFFF03 25%, #FFFFFF0D 37.5%, #FFFFFF14 43.75%, #FFFFFF17 50%, #FFFFFF14 56.25%, #FFFFFF0D 62.5%, #FFFFFF03 75%, #FFFFFF0D 87.5%, #FFFFFF14 93.75%, #FFFFFF17 100%);\n" +
  "  --on-dark-surface-skeleton-gradient-hover: #FFFFFFFF;\n" +
  "  --on-dark-surface-skeleton-gradient-active: #FFFFFFFF;\n" +
  "  --on-dark-surface-skeleton-deep-gradient: linear-gradient(90deg, #FFFFFF5C 0%, #FFFFFF52 6.25%, #FFFFFF33 12.5%, #FFFFFF0A 25%, #FFFFFF33 37.5%, #FFFFFF52 43.75%, #FFFFFF5C 50%, #FFFFFF14 56.25%, #FFFFFF33 62.5%, #FFFFFF0A 75%, #FFFFFF33 87.5%, #FFFFFF52 93.75%, #FFFFFF5C 100%);\n" +
  "  --on-dark-surface-skeleton-deep-gradient-hover: #FFFFFFFF;\n" +
  "  --on-dark-surface-skeleton-deep-gradient-active: #FFFFFFFF;\n" +
  "  --on-light-surface-accent-gradient-hover: #FFFFFFFF;\n" +
  "  --on-light-surface-accent-gradient-active: #FFFFFFFF;\n" +
  "  --on-light-surface-accent-gradient: linear-gradient(45.00deg, #0D8523FF 0%, #0DA8ABFF 100%);\n" +
  "  --on-light-surface-skeleton-gradient: linear-gradient(90deg, #08080817 0%, #08080814 6.25%, #0808080D 12.5%, #08080803 25%, #0808080D 37.5%, #08080814 43.75%, #08080817 50%, #08080814 56.25%, #0808080D 62.5%, #08080803 75%, #0808080D 87.5%, #08080814 93.75%, #08080817 100%);\n" +
  "  --on-light-surface-skeleton-gradient-hover: #FFFFFFFF;\n" +
  "  --on-light-surface-skeleton-gradient-active: #FFFFFFFF;\n" +
  "  --on-light-surface-skeleton-deep-gradient: linear-gradient(90deg, #0808085C 0%, #08080852 6.25%, #08080833 12.5%, #0808080A 25%, #08080833 37.5%, #08080852 43.75%, #0808085C 50%, #08080814 56.25%, #08080833 62.5%, #0808080A 75%, #08080833 87.5%, #08080852 93.75%, #0808085C 100%);\n" +
  "  --on-light-surface-skeleton-deep-gradient-hover: #FFFFFFFF;\n" +
  "  --on-light-surface-skeleton-deep-gradient-active: #FFFFFFFF;\n" +
  "  --inverse-surface-accent-gradient-hover: #FFFFFFFF;\n" +
  "  --inverse-surface-accent-gradient-active: #FFFFFFFF;\n" +
  "  --inverse-surface-accent-gradient: linear-gradient(45.00deg, #1A9E32FF 0.323%, #04C6C9FF 100%);\n" +
  "  --inverse-surface-skeleton-gradient: linear-gradient(90deg, #FFFFFF17 0%, #FFFFFF14 6.25%, #FFFFFF0D 12.5%, #FFFFFF03 25%, #FFFFFF0D 37.5%, #FFFFFF14 43.75%, #FFFFFF17 50%, #FFFFFF14 56.25%, #FFFFFF0D 62.5%, #FFFFFF03 75%, #FFFFFF0D 87.5%, #FFFFFF14 93.75%, #FFFFFF17 100%);\n" +
  "  --inverse-surface-skeleton-gradient-hover: #FFFFFFFF;\n" +
  "  --inverse-surface-skeleton-gradient-active: #FFFFFFFF;\n" +
  "  --inverse-surface-skeleton-deep-gradient: linear-gradient(90deg, #FFFFFF5C 0%, #FFFFFF52 6.25%, #FFFFFF33 12.5%, #FFFFFF0A 25%, #FFFFFF33 37.5%, #FFFFFF52 43.75%, #FFFFFF5C 50%, #FFFFFF14 56.25%, #FFFFFF33 62.5%, #FFFFFF0A 75%, #FFFFFF33 87.5%, #FFFFFF52 93.75%, #FFFFFF5C 100%);\n" +
  "  --inverse-surface-skeleton-deep-gradient-hover: #FFFFFFFF;\n" +
  "  --inverse-surface-skeleton-deep-gradient-active: #FFFFFFFF;\n" +
  "  --outline-accent-gradient-hover: #000000FF;\n" +
  "  --outline-accent-gradient-active: #CCCCCCFF;\n" +
  "  --outline-accent-minor-gradient-hover: #000000FF;\n" +
  "  --outline-accent-minor-gradient-active: #CCCCCCFF;\n" +
  "  --outline-transparent-accent-gradient-hover: #000000FF;\n" +
  "  --outline-transparent-accent-gradient-active: #CCCCCCFF;\n" +
  "  --outline-promo-gradient-hover: #000000FF;\n" +
  "  --outline-promo-gradient-active: #CCCCCCFF;\n" +
  "  --outline-promo-minor-gradient-hover: #000000FF;\n" +
  "  --outline-promo-minor-gradient-active: #CCCCCCFF;\n" +
  "  --outline-accent-gradient: linear-gradient(45.00deg, #0D8523FF 0%, #0DA8ABFF 100%);\n" +
  "  --on-dark-outline-accent-gradient-hover: #000000FF;\n" +
  "  --on-dark-outline-accent-gradient-active: #CCCCCCFF;\n" +
  "  --on-dark-outline-accent-minor-gradient-hover: #000000FF;\n" +
  "  --on-dark-outline-accent-minor-gradient-active: #CCCCCCFF;\n" +
  "  --on-dark-outline-transparent-accent-gradient-hover: #000000FF;\n" +
  "  --on-dark-outline-transparent-accent-gradient-active: #CCCCCCFF;\n" +
  "  --on-dark-outline-promo-gradient-hover: #000000FF;\n" +
  "  --on-dark-outline-promo-gradient-active: #CCCCCCFF;\n" +
  "  --on-dark-outline-promo-minor-gradient-hover: #000000FF;\n" +
  "  --on-dark-outline-promo-minor-gradient-active: #CCCCCCFF;\n" +
  "  --on-dark-outline-accent-gradient: linear-gradient(45.00deg, #1A9E32FF 0%, #04C6C9FF 99.688%);\n" +
  "  --on-light-outline-accent-gradient-hover: #000000FF;\n" +
  "  --on-light-outline-accent-gradient-active: #CCCCCCFF;\n" +
  "  --on-light-outline-accent-minor-gradient-hover: #000000FF;\n" +
  "  --on-light-outline-accent-minor-gradient-active: #CCCCCCFF;\n" +
  "  --on-light-outline-transparent-accent-gradient-hover: #000000FF;\n" +
  "  --on-light-outline-transparent-accent-gradient-active: #CCCCCCFF;\n" +
  "  --on-light-outline-promo-gradient-hover: #000000FF;\n" +
  "  --on-light-outline-promo-gradient-active: #CCCCCCFF;\n" +
  "  --on-light-outline-promo-minor-gradient-hover: #000000FF;\n" +
  "  --on-light-outline-promo-minor-gradient-active: #CCCCCCFF;\n" +
  "  --on-light-outline-accent-gradient: linear-gradient(45.00deg, #0D8523FF 0%, #0DA8ABFF 100%);\n" +
  "  --inverse-outline-accent-gradient-hover: #000000FF;\n" +
  "  --inverse-outline-accent-gradient-active: #CCCCCCFF;\n" +
  "  --inverse-outline-accent-minor-gradient-hover: #000000FF;\n" +
  "  --inverse-outline-accent-minor-gradient-active: #CCCCCCFF;\n" +
  "  --inverse-outline-transparent-accent-gradient-hover: #000000FF;\n" +
  "  --inverse-outline-transparent-accent-gradient-active: #CCCCCCFF;\n" +
  "  --inverse-outline-promo-gradient-hover: #000000FF;\n" +
  "  --inverse-outline-promo-gradient-active: #CCCCCCFF;\n" +
  "  --inverse-outline-promo-minor-gradient-hover: #000000FF;\n" +
  "  --inverse-outline-promo-minor-gradient-active: #CCCCCCFF;\n" +
  "  --inverse-outline-accent-gradient: linear-gradient(45.00deg, #1A9E32FF 0%, #04C6C9FF 99.688%);\n" +
  "}\n" +
  "\n" +
  ":root {\n" +
  "  --shadow-down-soft-s: 0px 4px 14px -4px #08080814, 0px 1px 4px -1px #0000000A;\n" +
  "  --shadow-down-soft-m: 0px 24px 48px -8px #00000014;\n" +
  "  --shadow-down-soft-l: 0px 60px 112px -8px #00000014;\n" +
  "  --shadow-down-hard-s: 0px 4px 12px -3px #08080829, 0px 1px 4px -2px #00000014;\n" +
  "  --shadow-down-hard-m: 0px 16px 32px -8px #0000003D;\n" +
  "  --shadow-down-hard-l: 0px 60px 112px -8px #00000066;\n" +
  "  --shadow-up-soft-s: 0px -4px 14px -4px #08080814, 0px -1px 4px -1px #00000008;\n" +
  "  --shadow-up-soft-m: 0px -24px 48px -8px #00000014;\n" +
  "  --shadow-up-soft-l: 0px -60px 112px -8px #00000014;\n" +
  "  --shadow-up-hard-s: 0px -4px 12px -3px #08080833, 0px -1px 4px -1px #00000008;\n" +
  "  --shadow-up-hard-m: 0px -16px 32px -8px #0000003D;\n" +
  "  --shadow-up-hard-l: 0px -60px 112px -8px #00000066;\n" +
  "}\n" +
  "\n" +
  ":root {\n" +
  "  --border-radius-xxs: 4px;\n" +
  "  --border-radius-xs: 8px;\n" +
  "  --border-radius-s: 12px;\n" +
  "  --border-radius-m: 16px;\n" +
  "  --border-radius-l: 20px;\n" +
  "  --border-radius-xl: 24px;\n" +
  "  --border-radius-xxl: 32px;\n" +
  "}\n" +
  "\n" +
  ":root {\n" +
  "  font-size: 16px;\n" +
  "  --plasma-typo-overflow-wrap: break-word;\n" +
  "  --plasma-typo-hyphens: auto;\n" +
  "  --plasma-typo-display-font-family: 'SB Sans Display', sans-serif;\n" +
  "  --plasma-typo-body-font-family: 'SB Sans Text', sans-serif;\n" +
  "  --plasma-typo-header-font-family: 'SB Sans Display', sans-serif;\n" +
  "  --plasma-typo-text-font-family: 'SB Sans Text', sans-serif;\n" +
  "  --plasma-typo-dspl-l-font-family: var(--plasma-typo-display-font-family);\n" +
  "  --plasma-typo-dspl-l-letter-spacing: normal;\n" +
  "  --plasma-typo-dspl-l-font-style: normal;\n" +
  "  --plasma-typo-dspl-l-bold-font-family: var(--plasma-typo-display-font-family);\n" +
  "  --plasma-typo-dspl-l-bold-letter-spacing: normal;\n" +
  "  --plasma-typo-dspl-l-bold-font-style: normal;\n" +
  "  --plasma-typo-dspl-m-font-family: var(--plasma-typo-display-font-family);\n" +
  "  --plasma-typo-dspl-m-letter-spacing: normal;\n" +
  "  --plasma-typo-dspl-m-font-style: normal;\n" +
  "  --plasma-typo-dspl-m-bold-font-family: var(--plasma-typo-display-font-family);\n" +
  "  --plasma-typo-dspl-m-bold-letter-spacing: normal;\n" +
  "  --plasma-typo-dspl-m-bold-font-style: normal;\n" +
  "  --plasma-typo-dspl-s-font-family: var(--plasma-typo-display-font-family);\n" +
  "  --plasma-typo-dspl-s-letter-spacing: normal;\n" +
  "  --plasma-typo-dspl-s-font-style: normal;\n" +
  "  --plasma-typo-dspl-s-bold-font-family: var(--plasma-typo-display-font-family);\n" +
  "  --plasma-typo-dspl-s-bold-letter-spacing: normal;\n" +
  "  --plasma-typo-dspl-s-bold-font-style: normal;\n" +
  "  --plasma-typo-h1-font-family: var(--plasma-typo-header-font-family);\n" +
  "  --plasma-typo-h1-letter-spacing: normal;\n" +
  "  --plasma-typo-h1-font-style: normal;\n" +
  "  --plasma-typo-h1-bold-font-family: var(--plasma-typo-header-font-family);\n" +
  "  --plasma-typo-h1-bold-letter-spacing: normal;\n" +
  "  --plasma-typo-h1-bold-font-style: normal;\n" +
  "  --plasma-typo-h2-font-family: var(--plasma-typo-header-font-family);\n" +
  "  --plasma-typo-h2-letter-spacing: normal;\n" +
  "  --plasma-typo-h2-font-style: normal;\n" +
  "  --plasma-typo-h2-bold-font-family: var(--plasma-typo-header-font-family);\n" +
  "  --plasma-typo-h2-bold-letter-spacing: normal;\n" +
  "  --plasma-typo-h2-bold-font-style: normal;\n" +
  "  --plasma-typo-h3-font-family: var(--plasma-typo-header-font-family);\n" +
  "  --plasma-typo-h3-letter-spacing: normal;\n" +
  "  --plasma-typo-h3-font-style: normal;\n" +
  "  --plasma-typo-h3-bold-font-family: var(--plasma-typo-header-font-family);\n" +
  "  --plasma-typo-h3-bold-letter-spacing: normal;\n" +
  "  --plasma-typo-h3-bold-font-style: normal;\n" +
  "  --plasma-typo-h4-font-family: var(--plasma-typo-header-font-family);\n" +
  "  --plasma-typo-h4-letter-spacing: normal;\n" +
  "  --plasma-typo-h4-font-style: normal;\n" +
  "  --plasma-typo-h4-bold-font-family: var(--plasma-typo-header-font-family);\n" +
  "  --plasma-typo-h4-bold-letter-spacing: normal;\n" +
  "  --plasma-typo-h4-bold-font-style: normal;\n" +
  "  --plasma-typo-h5-font-family: var(--plasma-typo-header-font-family);\n" +
  "  --plasma-typo-h5-letter-spacing: normal;\n" +
  "  --plasma-typo-h5-font-style: normal;\n" +
  "  --plasma-typo-h5-bold-font-family: var(--plasma-typo-header-font-family);\n" +
  "  --plasma-typo-h5-bold-letter-spacing: normal;\n" +
  "  --plasma-typo-h5-bold-font-style: normal;\n" +
  "  --plasma-typo-body-l-font-family: var(--plasma-typo-body-font-family);\n" +
  "  --plasma-typo-body-l-letter-spacing: -0.02em;\n" +
  "  --plasma-typo-body-l-font-style: normal;\n" +
  "  --plasma-typo-body-l-bold-font-family: var(--plasma-typo-body-font-family);\n" +
  "  --plasma-typo-body-l-bold-letter-spacing: -0.02em;\n" +
  "  --plasma-typo-body-l-bold-font-style: normal;\n" +
  "  --plasma-typo-body-m-font-family: var(--plasma-typo-body-font-family);\n" +
  "  --plasma-typo-body-m-letter-spacing: -0.02em;\n" +
  "  --plasma-typo-body-m-font-style: normal;\n" +
  "  --plasma-typo-body-m-bold-font-family: var(--plasma-typo-body-font-family);\n" +
  "  --plasma-typo-body-m-bold-letter-spacing: -0.02em;\n" +
  "  --plasma-typo-body-m-bold-font-style: normal;\n" +
  "  --plasma-typo-body-s-font-family: var(--plasma-typo-body-font-family);\n" +
  "  --plasma-typo-body-s-letter-spacing: -0.02em;\n" +
  "  --plasma-typo-body-s-font-style: normal;\n" +
  "  --plasma-typo-body-s-bold-font-family: var(--plasma-typo-body-font-family);\n" +
  "  --plasma-typo-body-s-bold-letter-spacing: -0.02em;\n" +
  "  --plasma-typo-body-s-bold-font-style: normal;\n" +
  "  --plasma-typo-body-xs-font-family: var(--plasma-typo-body-font-family);\n" +
  "  --plasma-typo-body-xs-letter-spacing: -0.02em;\n" +
  "  --plasma-typo-body-xs-font-style: normal;\n" +
  "  --plasma-typo-body-xs-bold-font-family: var(--plasma-typo-body-font-family);\n" +
  "  --plasma-typo-body-xs-bold-letter-spacing: -0.02em;\n" +
  "  --plasma-typo-body-xs-bold-font-style: normal;\n" +
  "  --plasma-typo-body-xxs-font-family: var(--plasma-typo-body-font-family);\n" +
  "  --plasma-typo-body-xxs-letter-spacing: -0.02em;\n" +
  "  --plasma-typo-body-xxs-font-style: normal;\n" +
  "  --plasma-typo-body-xxs-bold-font-family: var(--plasma-typo-body-font-family);\n" +
  "  --plasma-typo-body-xxs-bold-letter-spacing: -0.02em;\n" +
  "  --plasma-typo-body-xxs-bold-font-style: normal;\n" +
  "  --plasma-typo-text-l-font-family: var(--plasma-typo-text-font-family);\n" +
  "  --plasma-typo-text-l-letter-spacing: -0.02em;\n" +
  "  --plasma-typo-text-l-font-style: normal;\n" +
  "  --plasma-typo-text-l-bold-font-family: var(--plasma-typo-text-font-family);\n" +
  "  --plasma-typo-text-l-bold-letter-spacing: -0.02em;\n" +
  "  --plasma-typo-text-l-bold-font-style: normal;\n" +
  "  --plasma-typo-text-m-font-family: var(--plasma-typo-text-font-family);\n" +
  "  --plasma-typo-text-m-letter-spacing: -0.02em;\n" +
  "  --plasma-typo-text-m-font-style: normal;\n" +
  "  --plasma-typo-text-m-bold-font-family: var(--plasma-typo-text-font-family);\n" +
  "  --plasma-typo-text-m-bold-letter-spacing: -0.02em;\n" +
  "  --plasma-typo-text-m-bold-font-style: normal;\n" +
  "  --plasma-typo-text-s-font-family: var(--plasma-typo-text-font-family);\n" +
  "  --plasma-typo-text-s-letter-spacing: -0.02em;\n" +
  "  --plasma-typo-text-s-font-style: normal;\n" +
  "  --plasma-typo-text-s-bold-font-family: var(--plasma-typo-text-font-family);\n" +
  "  --plasma-typo-text-s-bold-letter-spacing: -0.02em;\n" +
  "  --plasma-typo-text-s-bold-font-style: normal;\n" +
  "  --plasma-typo-text-xs-font-family: var(--plasma-typo-text-font-family);\n" +
  "  --plasma-typo-text-xs-letter-spacing: -0.02em;\n" +
  "  --plasma-typo-text-xs-font-style: normal;\n" +
  "  --plasma-typo-text-xs-bold-font-family: var(--plasma-typo-text-font-family);\n" +
  "  --plasma-typo-text-xs-bold-letter-spacing: -0.02em;\n" +
  "  --plasma-typo-text-xs-bold-font-style: normal;\n" +
  "}\n" +
  "\n" +
  "@media (max-width: 559px) {\n" +
  "  :root {\n" +
  "    --plasma-typo-dspl-l-font-size: 5.5rem;\n" +
  "    --plasma-typo-dspl-l-font-weight: 300;\n" +
  "    --plasma-typo-dspl-l-line-height: 5.75rem;\n" +
  "    --plasma-typo-dspl-l-bold-font-size: 5.5rem;\n" +
  "    --plasma-typo-dspl-l-bold-font-weight: 600;\n" +
  "    --plasma-typo-dspl-l-bold-line-height: 5.75rem;\n" +
  "    --plasma-typo-dspl-m-font-size: 3.5rem;\n" +
  "    --plasma-typo-dspl-m-font-weight: 300;\n" +
  "    --plasma-typo-dspl-m-line-height: 3.875rem;\n" +
  "    --plasma-typo-dspl-m-bold-font-size: 3.5rem;\n" +
  "    --plasma-typo-dspl-m-bold-font-weight: 600;\n" +
  "    --plasma-typo-dspl-m-bold-line-height: 3.875rem;\n" +
  "    --plasma-typo-dspl-s-font-size: 2.5rem;\n" +
  "    --plasma-typo-dspl-s-font-weight: 300;\n" +
  "    --plasma-typo-dspl-s-line-height: 2.875rem;\n" +
  "    --plasma-typo-dspl-s-bold-font-size: 2.5rem;\n" +
  "    --plasma-typo-dspl-s-bold-font-weight: 600;\n" +
  "    --plasma-typo-dspl-s-bold-line-height: 2.875rem;\n" +
  "    --plasma-typo-h1-font-size: 1.75rem;\n" +
  "    --plasma-typo-h1-font-weight: 400;\n" +
  "    --plasma-typo-h1-line-height: 2.125rem;\n" +
  "    --plasma-typo-h1-bold-font-size: 1.75rem;\n" +
  "    --plasma-typo-h1-bold-font-weight: 600;\n" +
  "    --plasma-typo-h1-bold-line-height: 2.125rem;\n" +
  "    --plasma-typo-h2-font-size: 1.5rem;\n" +
  "    --plasma-typo-h2-font-weight: 400;\n" +
  "    --plasma-typo-h2-line-height: 1.875rem;\n" +
  "    --plasma-typo-h2-bold-font-size: 1.5rem;\n" +
  "    --plasma-typo-h2-bold-font-weight: 600;\n" +
  "    --plasma-typo-h2-bold-line-height: 1.875rem;\n" +
  "    --plasma-typo-h3-font-size: 1.25rem;\n" +
  "    --plasma-typo-h3-font-weight: 400;\n" +
  "    --plasma-typo-h3-line-height: 1.625rem;\n" +
  "    --plasma-typo-h3-bold-font-size: 1.25rem;\n" +
  "    --plasma-typo-h3-bold-font-weight: 600;\n" +
  "    --plasma-typo-h3-bold-line-height: 1.625rem;\n" +
  "    --plasma-typo-h4-font-size: 1.125rem;\n" +
  "    --plasma-typo-h4-font-weight: 400;\n" +
  "    --plasma-typo-h4-line-height: 1.5rem;\n" +
  "    --plasma-typo-h4-bold-font-size: 1.125rem;\n" +
  "    --plasma-typo-h4-bold-font-weight: 600;\n" +
  "    --plasma-typo-h4-bold-line-height: 1.5rem;\n" +
  "    --plasma-typo-h5-font-size: 1rem;\n" +
  "    --plasma-typo-h5-font-weight: 400;\n" +
  "    --plasma-typo-h5-line-height: 1.375rem;\n" +
  "    --plasma-typo-h5-bold-font-size: 1rem;\n" +
  "    --plasma-typo-h5-bold-font-weight: 600;\n" +
  "    --plasma-typo-h5-bold-line-height: 1.375rem;\n" +
  "    --plasma-typo-body-l-font-size: 1.125rem;\n" +
  "    --plasma-typo-body-l-font-weight: 400;\n" +
  "    --plasma-typo-body-l-line-height: 1.375rem;\n" +
  "    --plasma-typo-body-l-bold-font-size: 1.125rem;\n" +
  "    --plasma-typo-body-l-bold-font-weight: 600;\n" +
  "    --plasma-typo-body-l-bold-line-height: 1.375rem;\n" +
  "    --plasma-typo-body-m-font-size: 1rem;\n" +
  "    --plasma-typo-body-m-font-weight: 400;\n" +
  "    --plasma-typo-body-m-line-height: 1.25rem;\n" +
  "    --plasma-typo-body-m-bold-font-size: 1rem;\n" +
  "    --plasma-typo-body-m-bold-font-weight: 600;\n" +
  "    --plasma-typo-body-m-bold-line-height: 1.25rem;\n" +
  "    --plasma-typo-body-s-font-size: 0.875rem;\n" +
  "    --plasma-typo-body-s-font-weight: 400;\n" +
  "    --plasma-typo-body-s-line-height: 1.125rem;\n" +
  "    --plasma-typo-body-s-bold-font-size: 0.875rem;\n" +
  "    --plasma-typo-body-s-bold-font-weight: 600;\n" +
  "    --plasma-typo-body-s-bold-line-height: 1.125rem;\n" +
  "    --plasma-typo-body-xs-font-size: 0.75rem;\n" +
  "    --plasma-typo-body-xs-font-weight: 400;\n" +
  "    --plasma-typo-body-xs-line-height: 0.875rem;\n" +
  "    --plasma-typo-body-xs-bold-font-size: 0.75rem;\n" +
  "    --plasma-typo-body-xs-bold-font-weight: 600;\n" +
  "    --plasma-typo-body-xs-bold-line-height: 0.875rem;\n" +
  "    --plasma-typo-body-xxs-font-size: 0.625rem;\n" +
  "    --plasma-typo-body-xxs-font-weight: 400;\n" +
  "    --plasma-typo-body-xxs-line-height: 0.75rem;\n" +
  "    --plasma-typo-body-xxs-bold-font-size: 0.625rem;\n" +
  "    --plasma-typo-body-xxs-bold-font-weight: 600;\n" +
  "    --plasma-typo-body-xxs-bold-line-height: 0.75rem;\n" +
  "    --plasma-typo-text-l-font-size: 1.125rem;\n" +
  "    --plasma-typo-text-l-font-weight: 400;\n" +
  "    --plasma-typo-text-l-line-height: 1.625rem;\n" +
  "    --plasma-typo-text-l-bold-font-size: 1.125rem;\n" +
  "    --plasma-typo-text-l-bold-font-weight: 600;\n" +
  "    --plasma-typo-text-l-bold-line-height: 1.625rem;\n" +
  "    --plasma-typo-text-m-font-size: 1rem;\n" +
  "    --plasma-typo-text-m-font-weight: 400;\n" +
  "    --plasma-typo-text-m-line-height: 1.5rem;\n" +
  "    --plasma-typo-text-m-bold-font-size: 1rem;\n" +
  "    --plasma-typo-text-m-bold-font-weight: 600;\n" +
  "    --plasma-typo-text-m-bold-line-height: 1.5rem;\n" +
  "    --plasma-typo-text-s-font-size: 0.875rem;\n" +
  "    --plasma-typo-text-s-font-weight: 400;\n" +
  "    --plasma-typo-text-s-line-height: 1.25rem;\n" +
  "    --plasma-typo-text-s-bold-font-size: 0.875rem;\n" +
  "    --plasma-typo-text-s-bold-font-weight: 600;\n" +
  "    --plasma-typo-text-s-bold-line-height: 1.25rem;\n" +
  "    --plasma-typo-text-xs-font-size: 0.75rem;\n" +
  "    --plasma-typo-text-xs-font-weight: 400;\n" +
  "    --plasma-typo-text-xs-line-height: 1rem;\n" +
  "    --plasma-typo-text-xs-bold-font-size: 0.75rem;\n" +
  "    --plasma-typo-text-xs-bold-font-weight: 600;\n" +
  "    --plasma-typo-text-xs-bold-line-height: 1rem;\n" +
  "  }\n" +
  "}\n" +
  "\n" +
  "@media (min-width: 560px) and (max-width: 959px) {\n" +
  "  :root {\n" +
  "    --plasma-typo-dspl-l-font-size: 7rem;\n" +
  "    --plasma-typo-dspl-l-font-weight: 300;\n" +
  "    --plasma-typo-dspl-l-line-height: 7rem;\n" +
  "    --plasma-typo-dspl-l-bold-font-size: 7rem;\n" +
  "    --plasma-typo-dspl-l-bold-font-weight: 600;\n" +
  "    --plasma-typo-dspl-l-bold-line-height: 7rem;\n" +
  "    --plasma-typo-dspl-m-font-size: 4.5rem;\n" +
  "    --plasma-typo-dspl-m-font-weight: 300;\n" +
  "    --plasma-typo-dspl-m-line-height: 4.75rem;\n" +
  "    --plasma-typo-dspl-m-bold-font-size: 4.5rem;\n" +
  "    --plasma-typo-dspl-m-bold-font-weight: 600;\n" +
  "    --plasma-typo-dspl-m-bold-line-height: 4.75rem;\n" +
  "    --plasma-typo-dspl-s-font-size: 3rem;\n" +
  "    --plasma-typo-dspl-s-font-weight: 300;\n" +
  "    --plasma-typo-dspl-s-line-height: 3.375rem;\n" +
  "    --plasma-typo-dspl-s-bold-font-size: 3rem;\n" +
  "    --plasma-typo-dspl-s-bold-font-weight: 600;\n" +
  "    --plasma-typo-dspl-s-bold-line-height: 3.375rem;\n" +
  "    --plasma-typo-h1-font-size: 2.5rem;\n" +
  "    --plasma-typo-h1-font-weight: 400;\n" +
  "    --plasma-typo-h1-line-height: 2.875rem;\n" +
  "    --plasma-typo-h1-bold-font-size: 2.5rem;\n" +
  "    --plasma-typo-h1-bold-font-weight: 600;\n" +
  "    --plasma-typo-h1-bold-line-height: 2.875rem;\n" +
  "    --plasma-typo-h2-font-size: 1.75rem;\n" +
  "    --plasma-typo-h2-font-weight: 400;\n" +
  "    --plasma-typo-h2-line-height: 2.125rem;\n" +
  "    --plasma-typo-h2-bold-font-size: 1.75rem;\n" +
  "    --plasma-typo-h2-bold-font-weight: 600;\n" +
  "    --plasma-typo-h2-bold-line-height: 2.125rem;\n" +
  "    --plasma-typo-h3-font-size: 1.25rem;\n" +
  "    --plasma-typo-h3-font-weight: 400;\n" +
  "    --plasma-typo-h3-line-height: 1.625rem;\n" +
  "    --plasma-typo-h3-bold-font-size: 1.25rem;\n" +
  "    --plasma-typo-h3-bold-font-weight: 600;\n" +
  "    --plasma-typo-h3-bold-line-height: 1.625rem;\n" +
  "    --plasma-typo-h4-font-size: 1.125rem;\n" +
  "    --plasma-typo-h4-font-weight: 400;\n" +
  "    --plasma-typo-h4-line-height: 1.5rem;\n" +
  "    --plasma-typo-h4-bold-font-size: 1.125rem;\n" +
  "    --plasma-typo-h4-bold-font-weight: 600;\n" +
  "    --plasma-typo-h4-bold-line-height: 1.5rem;\n" +
  "    --plasma-typo-h5-font-size: 1rem;\n" +
  "    --plasma-typo-h5-font-weight: 400;\n" +
  "    --plasma-typo-h5-line-height: 1.375rem;\n" +
  "    --plasma-typo-h5-bold-font-size: 1rem;\n" +
  "    --plasma-typo-h5-bold-font-weight: 600;\n" +
  "    --plasma-typo-h5-bold-line-height: 1.375rem;\n" +
  "    --plasma-typo-body-l-font-size: 1.125rem;\n" +
  "    --plasma-typo-body-l-font-weight: 400;\n" +
  "    --plasma-typo-body-l-line-height: 1.375rem;\n" +
  "    --plasma-typo-body-l-bold-font-size: 1.125rem;\n" +
  "    --plasma-typo-body-l-bold-font-weight: 600;\n" +
  "    --plasma-typo-body-l-bold-line-height: 1.375rem;\n" +
  "    --plasma-typo-body-m-font-size: 1rem;\n" +
  "    --plasma-typo-body-m-font-weight: 400;\n" +
  "    --plasma-typo-body-m-line-height: 1.25rem;\n" +
  "    --plasma-typo-body-m-bold-font-size: 1rem;\n" +
  "    --plasma-typo-body-m-bold-font-weight: 600;\n" +
  "    --plasma-typo-body-m-bold-line-height: 1.25rem;\n" +
  "    --plasma-typo-body-s-font-size: 0.875rem;\n" +
  "    --plasma-typo-body-s-font-weight: 400;\n" +
  "    --plasma-typo-body-s-line-height: 1.125rem;\n" +
  "    --plasma-typo-body-s-bold-font-size: 0.875rem;\n" +
  "    --plasma-typo-body-s-bold-font-weight: 600;\n" +
  "    --plasma-typo-body-s-bold-line-height: 1.125rem;\n" +
  "    --plasma-typo-body-xs-font-size: 0.75rem;\n" +
  "    --plasma-typo-body-xs-font-weight: 400;\n" +
  "    --plasma-typo-body-xs-line-height: 0.875rem;\n" +
  "    --plasma-typo-body-xs-bold-font-size: 0.75rem;\n" +
  "    --plasma-typo-body-xs-bold-font-weight: 600;\n" +
  "    --plasma-typo-body-xs-bold-line-height: 0.875rem;\n" +
  "    --plasma-typo-body-xxs-font-size: 0.625rem;\n" +
  "    --plasma-typo-body-xxs-font-weight: 400;\n" +
  "    --plasma-typo-body-xxs-line-height: 0.75rem;\n" +
  "    --plasma-typo-body-xxs-bold-font-size: 0.625rem;\n" +
  "    --plasma-typo-body-xxs-bold-font-weight: 600;\n" +
  "    --plasma-typo-body-xxs-bold-line-height: 0.75rem;\n" +
  "    --plasma-typo-text-l-font-size: 1.25rem;\n" +
  "    --plasma-typo-text-l-font-weight: 400;\n" +
  "    --plasma-typo-text-l-line-height: 1.75rem;\n" +
  "    --plasma-typo-text-l-bold-font-size: 1.25rem;\n" +
  "    --plasma-typo-text-l-bold-font-weight: 600;\n" +
  "    --plasma-typo-text-l-bold-line-height: 1.75rem;\n" +
  "    --plasma-typo-text-m-font-size: 1rem;\n" +
  "    --plasma-typo-text-m-font-weight: 400;\n" +
  "    --plasma-typo-text-m-line-height: 1.5rem;\n" +
  "    --plasma-typo-text-m-bold-font-size: 1rem;\n" +
  "    --plasma-typo-text-m-bold-font-weight: 600;\n" +
  "    --plasma-typo-text-m-bold-line-height: 1.5rem;\n" +
  "    --plasma-typo-text-s-font-size: 0.875rem;\n" +
  "    --plasma-typo-text-s-font-weight: 400;\n" +
  "    --plasma-typo-text-s-line-height: 1.25rem;\n" +
  "    --plasma-typo-text-s-bold-font-size: 0.875rem;\n" +
  "    --plasma-typo-text-s-bold-font-weight: 600;\n" +
  "    --plasma-typo-text-s-bold-line-height: 1.25rem;\n" +
  "    --plasma-typo-text-xs-font-size: 0.75rem;\n" +
  "    --plasma-typo-text-xs-font-weight: 400;\n" +
  "    --plasma-typo-text-xs-line-height: 1rem;\n" +
  "    --plasma-typo-text-xs-bold-font-size: 0.75rem;\n" +
  "    --plasma-typo-text-xs-bold-font-weight: 600;\n" +
  "    --plasma-typo-text-xs-bold-line-height: 1rem;\n" +
  "  }\n" +
  "}\n" +
  "\n" +
  "@media (min-width: 960px) {\n" +
  "  :root {\n" +
  "    --plasma-typo-dspl-l-font-size: 8rem;\n" +
  "    --plasma-typo-dspl-l-font-weight: 300;\n" +
  "    --plasma-typo-dspl-l-line-height: 8rem;\n" +
  "    --plasma-typo-dspl-l-bold-font-size: 8rem;\n" +
  "    --plasma-typo-dspl-l-bold-font-weight: 600;\n" +
  "    --plasma-typo-dspl-l-bold-line-height: 8rem;\n" +
  "    --plasma-typo-dspl-m-font-size: 5.5rem;\n" +
  "    --plasma-typo-dspl-m-font-weight: 300;\n" +
  "    --plasma-typo-dspl-m-line-height: 5.75rem;\n" +
  "    --plasma-typo-dspl-m-bold-font-size: 5.5rem;\n" +
  "    --plasma-typo-dspl-m-bold-font-weight: 600;\n" +
  "    --plasma-typo-dspl-m-bold-line-height: 5.75rem;\n" +
  "    --plasma-typo-dspl-s-font-size: 4rem;\n" +
  "    --plasma-typo-dspl-s-font-weight: 300;\n" +
  "    --plasma-typo-dspl-s-line-height: 4.25rem;\n" +
  "    --plasma-typo-dspl-s-bold-font-size: 4rem;\n" +
  "    --plasma-typo-dspl-s-bold-font-weight: 600;\n" +
  "    --plasma-typo-dspl-s-bold-line-height: 4.25rem;\n" +
  "    --plasma-typo-h1-font-size: 3rem;\n" +
  "    --plasma-typo-h1-font-weight: 400;\n" +
  "    --plasma-typo-h1-line-height: 3.375rem;\n" +
  "    --plasma-typo-h1-bold-font-size: 3rem;\n" +
  "    --plasma-typo-h1-bold-font-weight: 600;\n" +
  "    --plasma-typo-h1-bold-line-height: 3.375rem;\n" +
  "    --plasma-typo-h2-font-size: 2rem;\n" +
  "    --plasma-typo-h2-font-weight: 400;\n" +
  "    --plasma-typo-h2-line-height: 2.375rem;\n" +
  "    --plasma-typo-h2-bold-font-size: 2rem;\n" +
  "    --plasma-typo-h2-bold-font-weight: 600;\n" +
  "    --plasma-typo-h2-bold-line-height: 2.375rem;\n" +
  "    --plasma-typo-h3-font-size: 1.5rem;\n" +
  "    --plasma-typo-h3-font-weight: 400;\n" +
  "    --plasma-typo-h3-line-height: 1.875rem;\n" +
  "    --plasma-typo-h3-bold-font-size: 1.5rem;\n" +
  "    --plasma-typo-h3-bold-font-weight: 600;\n" +
  "    --plasma-typo-h3-bold-line-height: 1.875rem;\n" +
  "    --plasma-typo-h4-font-size: 1.25rem;\n" +
  "    --plasma-typo-h4-font-weight: 400;\n" +
  "    --plasma-typo-h4-line-height: 1.625rem;\n" +
  "    --plasma-typo-h4-bold-font-size: 1.25rem;\n" +
  "    --plasma-typo-h4-bold-font-weight: 600;\n" +
  "    --plasma-typo-h4-bold-line-height: 1.625rem;\n" +
  "    --plasma-typo-h5-font-size: 1.125rem;\n" +
  "    --plasma-typo-h5-font-weight: 400;\n" +
  "    --plasma-typo-h5-line-height: 1.5rem;\n" +
  "    --plasma-typo-h5-bold-font-size: 1.125rem;\n" +
  "    --plasma-typo-h5-bold-font-weight: 600;\n" +
  "    --plasma-typo-h5-bold-line-height: 1.5rem;\n" +
  "    --plasma-typo-body-l-font-size: 1.125rem;\n" +
  "    --plasma-typo-body-l-font-weight: 400;\n" +
  "    --plasma-typo-body-l-line-height: 1.375rem;\n" +
  "    --plasma-typo-body-l-bold-font-size: 1.125rem;\n" +
  "    --plasma-typo-body-l-bold-font-weight: 600;\n" +
  "    --plasma-typo-body-l-bold-line-height: 1.375rem;\n" +
  "    --plasma-typo-body-m-font-size: 1rem;\n" +
  "    --plasma-typo-body-m-font-weight: 400;\n" +
  "    --plasma-typo-body-m-line-height: 1.25rem;\n" +
  "    --plasma-typo-body-m-bold-font-size: 1rem;\n" +
  "    --plasma-typo-body-m-bold-font-weight: 600;\n" +
  "    --plasma-typo-body-m-bold-line-height: 1.25rem;\n" +
  "    --plasma-typo-body-s-font-size: 0.875rem;\n" +
  "    --plasma-typo-body-s-font-weight: 400;\n" +
  "    --plasma-typo-body-s-line-height: 1.125rem;\n" +
  "    --plasma-typo-body-s-bold-font-size: 0.875rem;\n" +
  "    --plasma-typo-body-s-bold-font-weight: 600;\n" +
  "    --plasma-typo-body-s-bold-line-height: 1.125rem;\n" +
  "    --plasma-typo-body-xs-font-size: 0.75rem;\n" +
  "    --plasma-typo-body-xs-font-weight: 400;\n" +
  "    --plasma-typo-body-xs-line-height: 0.875rem;\n" +
  "    --plasma-typo-body-xs-bold-font-size: 0.75rem;\n" +
  "    --plasma-typo-body-xs-bold-font-weight: 600;\n" +
  "    --plasma-typo-body-xs-bold-line-height: 0.875rem;\n" +
  "    --plasma-typo-body-xxs-font-size: 0.625rem;\n" +
  "    --plasma-typo-body-xxs-font-weight: 400;\n" +
  "    --plasma-typo-body-xxs-line-height: 0.75rem;\n" +
  "    --plasma-typo-body-xxs-bold-font-size: 0.625rem;\n" +
  "    --plasma-typo-body-xxs-bold-font-weight: 600;\n" +
  "    --plasma-typo-body-xxs-bold-line-height: 0.75rem;\n" +
  "    --plasma-typo-text-l-font-size: 1.5rem;\n" +
  "    --plasma-typo-text-l-font-weight: 400;\n" +
  "    --plasma-typo-text-l-line-height: 2rem;\n" +
  "    --plasma-typo-text-l-bold-font-size: 1.5rem;\n" +
  "    --plasma-typo-text-l-bold-font-weight: 600;\n" +
  "    --plasma-typo-text-l-bold-line-height: 2rem;\n" +
  "    --plasma-typo-text-m-font-size: 1.125rem;\n" +
  "    --plasma-typo-text-m-font-weight: 400;\n" +
  "    --plasma-typo-text-m-line-height: 1.625rem;\n" +
  "    --plasma-typo-text-m-bold-font-size: 1.125rem;\n" +
  "    --plasma-typo-text-m-bold-font-weight: 600;\n" +
  "    --plasma-typo-text-m-bold-line-height: 1.625rem;\n" +
  "    --plasma-typo-text-s-font-size: 0.875rem;\n" +
  "    --plasma-typo-text-s-font-weight: 400;\n" +
  "    --plasma-typo-text-s-line-height: 1.25rem;\n" +
  "    --plasma-typo-text-s-bold-font-size: 0.875rem;\n" +
  "    --plasma-typo-text-s-bold-font-weight: 600;\n" +
  "    --plasma-typo-text-s-bold-line-height: 1.25rem;\n" +
  "    --plasma-typo-text-xs-font-size: 0.75rem;\n" +
  "    --plasma-typo-text-xs-font-weight: 400;\n" +
  "    --plasma-typo-text-xs-line-height: 1rem;\n" +
  "    --plasma-typo-text-xs-bold-font-size: 0.75rem;\n" +
  "    --plasma-typo-text-xs-bold-font-weight: 600;\n" +
  "    --plasma-typo-text-xs-bold-line-height: 1rem;\n" +
  "  }\n" +
  "}"
